//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace HmjNew.Service
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_DynMemberBunding_obBinding", Namespace="http://jahwa.com/pos/crm")]
    public partial class si_DynMemberBunding_obService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_DynMemberBunding_obOperationCompleted;
        
        /// <remarks/>
        public si_DynMemberBunding_obService() {
            this.Url = ConfigurationManager.AppSettings["WebServerURL"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_DynMemberBunding_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUser"],
            ConfigurationManager.AppSettings["WebServerPass"]);
        }
        
        /// <remarks/>
        public event si_DynMemberBunding_obCompletedEventHandler si_DynMemberBunding_obCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_DynMemberBunding_res", Namespace="http://jahwa.com/pos/crm")]
        public dt_DynMemberBunding_res si_DynMemberBunding_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")]
        dt_DynMemberBunding_req mt_DynMemberBunding_req) {
            object[] results = this.Invoke("si_DynMemberBunding_ob", new object[] {
                        mt_DynMemberBunding_req});
            return ((dt_DynMemberBunding_res)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsi_DynMemberBunding_ob(dt_DynMemberBunding_req mt_DynMemberBunding_req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("si_DynMemberBunding_ob", new object[] {
                        mt_DynMemberBunding_req}, callback, asyncState);
        }
        
        /// <remarks/>
        public dt_DynMemberBunding_res Endsi_DynMemberBunding_ob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_DynMemberBunding_res)(results[0]));
        }
        
        /// <remarks/>
        public void si_DynMemberBunding_obAsync(dt_DynMemberBunding_req mt_DynMemberBunding_req) {
            this.si_DynMemberBunding_obAsync(mt_DynMemberBunding_req, null);
        }
        
        /// <remarks/>
        public void si_DynMemberBunding_obAsync(dt_DynMemberBunding_req mt_DynMemberBunding_req, object userState) {
            if ((this.si_DynMemberBunding_obOperationCompleted == null)) {
                this.si_DynMemberBunding_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_DynMemberBunding_obOperationCompleted);
            }
            this.InvokeAsync("si_DynMemberBunding_ob", new object[] {
                        mt_DynMemberBunding_req}, this.si_DynMemberBunding_obOperationCompleted, userState);
        }
        
        private void Onsi_DynMemberBunding_obOperationCompleted(object arg) {
            if ((this.si_DynMemberBunding_obCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_DynMemberBunding_obCompleted(this, new si_DynMemberBunding_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_DynMemberBunding_req {
        
        private string vGROUPField;
        
        private string dATA_SOURCEField;
        
        private string sOURCE_SYSTEMField;
        
        private string lOYALTY_BRANDField;
        
        private string mEMBER_IDField;
        
        private dt_DynMemberBunding_reqITEM[] bRANDMEMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP {
            get {
                return this.vGROUPField;
            }
            set {
                this.vGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE {
            get {
                return this.dATA_SOURCEField;
            }
            set {
                this.dATA_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM {
            get {
                return this.sOURCE_SYSTEMField;
            }
            set {
                this.sOURCE_SYSTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND {
            get {
                return this.lOYALTY_BRANDField;
            }
            set {
                this.lOYALTY_BRANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMBER_ID {
            get {
                return this.mEMBER_IDField;
            }
            set {
                this.mEMBER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_DynMemberBunding_reqITEM[] BRANDMEMBER {
            get {
                return this.bRANDMEMBERField;
            }
            set {
                this.bRANDMEMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_DynMemberBunding_reqITEM {
        
        private string vGROUP2Field;
        
        private string dATA_SOURCE2Field;
        
        private string lOYALTY_BRAND2Field;
        
        private string mEMBER_ID2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP2 {
            get {
                return this.vGROUP2Field;
            }
            set {
                this.vGROUP2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE2 {
            get {
                return this.dATA_SOURCE2Field;
            }
            set {
                this.dATA_SOURCE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND2 {
            get {
                return this.lOYALTY_BRAND2Field;
            }
            set {
                this.lOYALTY_BRAND2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMBER_ID2 {
            get {
                return this.mEMBER_ID2Field;
            }
            set {
                this.mEMBER_ID2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_DynMemberBunding_res {
        
        private string zRETURNField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRETURN {
            get {
                return this.zRETURNField;
            }
            set {
                this.zRETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_DynMemberBunding_obCompletedEventHandler(object sender, si_DynMemberBunding_obCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_DynMemberBunding_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal si_DynMemberBunding_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_DynMemberBunding_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_DynMemberBunding_res)(this.results[0]));
            }
        }
    }
}
