//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace HmjNew.Service
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_Dyn_CreateLead_obBinding", Namespace="http://jahwa.com/pos/crm")]
    public partial class si_Dyn_CreateLead_obService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_Dyn_CreateLead_obOperationCompleted;
        
        /// <remarks/>
        public si_Dyn_CreateLead_obService() {
            this.Url = ConfigurationManager.AppSettings["WebServerURL"]+"/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_CreateLead_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUser"],
            ConfigurationManager.AppSettings["WebServerPass"]);
        }
        
        /// <remarks/>
        public event si_Dyn_CreateLead_obCompletedEventHandler si_Dyn_CreateLead_obCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_CreateLead_res", Namespace="http://jahwa.com/pos/crm")]
        public dt_Dyn_CreateLead_res si_Dyn_CreateLead_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")]
        dt_Dyn_CreateLead_req mt_Dyn_CreateLead_req) {
            object[] results = this.Invoke("si_Dyn_CreateLead_ob", new object[] {
                        mt_Dyn_CreateLead_req});
            return ((dt_Dyn_CreateLead_res)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsi_Dyn_CreateLead_ob(dt_Dyn_CreateLead_req mt_Dyn_CreateLead_req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("si_Dyn_CreateLead_ob", new object[] {
                        mt_Dyn_CreateLead_req}, callback, asyncState);
        }
        
        /// <remarks/>
        public dt_Dyn_CreateLead_res Endsi_Dyn_CreateLead_ob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_CreateLead_res)(results[0]));
        }
        
        /// <remarks/>
        public void si_Dyn_CreateLead_obAsync(dt_Dyn_CreateLead_req mt_Dyn_CreateLead_req) {
            this.si_Dyn_CreateLead_obAsync(mt_Dyn_CreateLead_req, null);
        }
        
        /// <remarks/>
        public void si_Dyn_CreateLead_obAsync(dt_Dyn_CreateLead_req mt_Dyn_CreateLead_req, object userState) {
            if ((this.si_Dyn_CreateLead_obOperationCompleted == null)) {
                this.si_Dyn_CreateLead_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_Dyn_CreateLead_obOperationCompleted);
            }
            this.InvokeAsync("si_Dyn_CreateLead_ob", new object[] {
                        mt_Dyn_CreateLead_req}, this.si_Dyn_CreateLead_obOperationCompleted, userState);
        }
        
        private void Onsi_Dyn_CreateLead_obOperationCompleted(object arg) {
            if ((this.si_Dyn_CreateLead_obCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_Dyn_CreateLead_obCompleted(this, new si_Dyn_CreateLead_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_CreateLead_req {
        
        private ZCRMT342_Dyn[] iNFO_QKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCRMT342_Dyn[] INFO_QK {
            get {
                return this.iNFO_QKField;
            }
            set {
                this.iNFO_QKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class ZCRMT342_Dyn {
        
        private string mOB_NUMBERField;
        
        private string vGROUPField;
        
        private string lOYALTY_BRANDField;
        
        private string iN_DATEField;
        
        //private bool iN_DATEFieldSpecified;
        
        private string nAME1_TEXTField;
        
        private string nICKNAMEField;
        
        private string nAMCOUNTRYField;
        
        private string rEGION_TEXTField;
        
        private string cITYField;
        
        private string xSEXField;
        
        private string bIRTHDTField;
        
        private string jOBGRField;
        
        private string bUPA_IDTYPE_PRSField;
        
        private string iDNUMBERField;
        
        private string pOST_CODE1Field;
        
        private string tEL_NUMBERField;
        
        private string sMTP_ADDRField;
        
        private string qqField;
        
        private string mSNField;
        
        private string wEIBOField;
        
        private string wECHATField;
        
        private string oTHER_CONTACTField;
        
        private string iF_HYField;
        
        private string hY_CARDField;
        
        private string pSTREETField;
        
        private string rEG_DATEField;
        
        //private bool rEG_DATEFieldSpecified;
        
        private string iN_CHANNELField;
        
        private string aCT_REMARKField;
        
        private string oBJECT_IDField;
        
        private string iF_RECEIVEField;
        
        private string zC012Field;
        
        private string zC013Field;
        
        private string dEPTIDField;
        
        private string eMPIDField;
        
        private string cAMPAIGN_NAME1Field;
        
        private string cAMPAIGN_ID1Field;
        
        private string cAMPAIGN_DATE1Field;
        
        //private bool cAMPAIGN_DATE1FieldSpecified;
        
        private string cAMPAIGN_NAME2Field;
        
        private string cAMPAIGN_ID2Field;
        
        private string cAMPAIGN_DATE2Field;
        
        //private bool cAMPAIGN_DATE2FieldSpecified;
        
        private string sALES_ORDER_CRMField;
        
        private string sALES_ORDER_IDField;
        
        private string oPENIDField;
        
        private string dATA_SOURCEField;
        
        private string sOURCE_SYSTEMField;
        
        private string wECHATFOLLOWSTATUSField;
        
        private string wECHATNAMEField;
        
        private string wECHATVALIDField;
        
        private string cAREERField;
        
        private string bRAND_SOURCEField;
        
        private string cHANNEL_SOURCEField;
        
        private string aLI_NAMEField;
        
        private string jD_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOB_NUMBER {
            get {
                return this.mOB_NUMBERField;
            }
            set {
                this.mOB_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP {
            get {
                return this.vGROUPField;
            }
            set {
                this.vGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND {
            get {
                return this.lOYALTY_BRANDField;
            }
            set {
                this.lOYALTY_BRANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="string")]
        public string IN_DATE {
            get {
                return this.iN_DATEField;
            }
            set {
                this.iN_DATEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool IN_DATESpecified {
        //    get {
        //        return this.iN_DATEFieldSpecified;
        //    }
        //    set {
        //        this.iN_DATEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1_TEXT {
            get {
                return this.nAME1_TEXTField;
            }
            set {
                this.nAME1_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NICKNAME {
            get {
                return this.nICKNAMEField;
            }
            set {
                this.nICKNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAMCOUNTRY {
            get {
                return this.nAMCOUNTRYField;
            }
            set {
                this.nAMCOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGION_TEXT {
            get {
                return this.rEGION_TEXTField;
            }
            set {
                this.rEGION_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XSEX {
            get {
                return this.xSEXField;
            }
            set {
                this.xSEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIRTHDT {
            get {
                return this.bIRTHDTField;
            }
            set {
                this.bIRTHDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JOBGR {
            get {
                return this.jOBGRField;
            }
            set {
                this.jOBGRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUPA_IDTYPE_PRS {
            get {
                return this.bUPA_IDTYPE_PRSField;
            }
            set {
                this.bUPA_IDTYPE_PRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDNUMBER {
            get {
                return this.iDNUMBERField;
            }
            set {
                this.iDNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POST_CODE1 {
            get {
                return this.pOST_CODE1Field;
            }
            set {
                this.pOST_CODE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEL_NUMBER {
            get {
                return this.tEL_NUMBERField;
            }
            set {
                this.tEL_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SMTP_ADDR {
            get {
                return this.sMTP_ADDRField;
            }
            set {
                this.sMTP_ADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QQ {
            get {
                return this.qqField;
            }
            set {
                this.qqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSN {
            get {
                return this.mSNField;
            }
            set {
                this.mSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEIBO {
            get {
                return this.wEIBOField;
            }
            set {
                this.wEIBOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WECHAT {
            get {
                return this.wECHATField;
            }
            set {
                this.wECHATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTHER_CONTACT {
            get {
                return this.oTHER_CONTACTField;
            }
            set {
                this.oTHER_CONTACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IF_HY {
            get {
                return this.iF_HYField;
            }
            set {
                this.iF_HYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HY_CARD {
            get {
                return this.hY_CARDField;
            }
            set {
                this.hY_CARDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSTREET {
            get {
                return this.pSTREETField;
            }
            set {
                this.pSTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REG_DATE {
            get {
                return this.rEG_DATEField;
            }
            set {
                this.rEG_DATEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool REG_DATESpecified {
        //    get {
        //        return this.rEG_DATEFieldSpecified;
        //    }
        //    set {
        //        this.rEG_DATEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IN_CHANNEL {
            get {
                return this.iN_CHANNELField;
            }
            set {
                this.iN_CHANNELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACT_REMARK {
            get {
                return this.aCT_REMARKField;
            }
            set {
                this.aCT_REMARKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBJECT_ID {
            get {
                return this.oBJECT_IDField;
            }
            set {
                this.oBJECT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IF_RECEIVE {
            get {
                return this.iF_RECEIVEField;
            }
            set {
                this.iF_RECEIVEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC012 {
            get {
                return this.zC012Field;
            }
            set {
                this.zC012Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC013 {
            get {
                return this.zC013Field;
            }
            set {
                this.zC013Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPTID {
            get {
                return this.dEPTIDField;
            }
            set {
                this.dEPTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPID {
            get {
                return this.eMPIDField;
            }
            set {
                this.eMPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAMPAIGN_NAME1 {
            get {
                return this.cAMPAIGN_NAME1Field;
            }
            set {
                this.cAMPAIGN_NAME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAMPAIGN_ID1 {
            get {
                return this.cAMPAIGN_ID1Field;
            }
            set {
                this.cAMPAIGN_ID1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAMPAIGN_DATE1 {
            get {
                return this.cAMPAIGN_DATE1Field;
            }
            set {
                this.cAMPAIGN_DATE1Field = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool CAMPAIGN_DATE1Specified {
        //    get {
        //        return this.cAMPAIGN_DATE1FieldSpecified;
        //    }
        //    set {
        //        this.cAMPAIGN_DATE1FieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAMPAIGN_NAME2 {
            get {
                return this.cAMPAIGN_NAME2Field;
            }
            set {
                this.cAMPAIGN_NAME2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAMPAIGN_ID2 {
            get {
                return this.cAMPAIGN_ID2Field;
            }
            set {
                this.cAMPAIGN_ID2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAMPAIGN_DATE2 {
            get {
                return this.cAMPAIGN_DATE2Field;
            }
            set {
                this.cAMPAIGN_DATE2Field = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool CAMPAIGN_DATE2Specified {
        //    get {
        //        return this.cAMPAIGN_DATE2FieldSpecified;
        //    }
        //    set {
        //        this.cAMPAIGN_DATE2FieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALES_ORDER_CRM {
            get {
                return this.sALES_ORDER_CRMField;
            }
            set {
                this.sALES_ORDER_CRMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALES_ORDER_ID {
            get {
                return this.sALES_ORDER_IDField;
            }
            set {
                this.sALES_ORDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPENID {
            get {
                return this.oPENIDField;
            }
            set {
                this.oPENIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE {
            get {
                return this.dATA_SOURCEField;
            }
            set {
                this.dATA_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM {
            get {
                return this.sOURCE_SYSTEMField;
            }
            set {
                this.sOURCE_SYSTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WECHATFOLLOWSTATUS {
            get {
                return this.wECHATFOLLOWSTATUSField;
            }
            set {
                this.wECHATFOLLOWSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WECHATNAME {
            get {
                return this.wECHATNAMEField;
            }
            set {
                this.wECHATNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WECHATVALID {
            get {
                return this.wECHATVALIDField;
            }
            set {
                this.wECHATVALIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAREER {
            get {
                return this.cAREERField;
            }
            set {
                this.cAREERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRAND_SOURCE {
            get {
                return this.bRAND_SOURCEField;
            }
            set {
                this.bRAND_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHANNEL_SOURCE {
            get {
                return this.cHANNEL_SOURCEField;
            }
            set {
                this.cHANNEL_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ALI_NAME {
            get {
                return this.aLI_NAMEField;
            }
            set {
                this.aLI_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JD_NAME {
            get {
                return this.jD_NAMEField;
            }
            set {
                this.jD_NAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_CreateLead_res {
        
        private string wV_RETURNField;
        
        private string wV_MESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WV_RETURN {
            get {
                return this.wV_RETURNField;
            }
            set {
                this.wV_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WV_MESSAGE {
            get {
                return this.wV_MESSAGEField;
            }
            set {
                this.wV_MESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_Dyn_CreateLead_obCompletedEventHandler(object sender, si_Dyn_CreateLead_obCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_Dyn_CreateLead_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal si_Dyn_CreateLead_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_Dyn_CreateLead_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_CreateLead_res)(this.results[0]));
            }
        }
    }
}
