//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace HmjNew.Service
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_Dyn_ActCreateTel_obBinding", Namespace="http://jahwa.com/pos/crm")]
    public partial class si_Dyn_ActCreateTel_obService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_ActCreateTel_obOperationCompleted;
        
        /// <remarks/>
        public si_Dyn_ActCreateTel_obService() {
            this.Url = ConfigurationManager.AppSettings["WebServerURL"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_ActCreateTel_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUser"],
            ConfigurationManager.AppSettings["WebServerPass"]);
        }
        
        /// <remarks/>
        public event si_ActCreateTel_obCompletedEventHandler si_ActCreateTel_obCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_ActCreateTel_res", Namespace="http://jahwa.com/pos/ecc")]
        public dt_Dyn_ActCreateTel_res si_ActCreateTel_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/ecc")] dt_Dyn_ActCreateTel_req mt_Dyn_ActCreateTel_req) {
            object[] results = this.Invoke("si_ActCreateTel_ob", new object[] {
                        mt_Dyn_ActCreateTel_req});
            return ((dt_Dyn_ActCreateTel_res)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsi_ActCreateTel_ob(dt_Dyn_ActCreateTel_req mt_Dyn_ActCreateTel_req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("si_ActCreateTel_ob", new object[] {
                        mt_Dyn_ActCreateTel_req}, callback, asyncState);
        }
        
        /// <remarks/>
        public dt_Dyn_ActCreateTel_res Endsi_ActCreateTel_ob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_ActCreateTel_res)(results[0]));
        }
        
        /// <remarks/>
        public void si_ActCreateTel_obAsync(dt_Dyn_ActCreateTel_req mt_Dyn_ActCreateTel_req) {
            this.si_ActCreateTel_obAsync(mt_Dyn_ActCreateTel_req, null);
        }
        
        /// <remarks/>
        public void si_ActCreateTel_obAsync(dt_Dyn_ActCreateTel_req mt_Dyn_ActCreateTel_req, object userState) {
            if ((this.si_ActCreateTel_obOperationCompleted == null)) {
                this.si_ActCreateTel_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_ActCreateTel_obOperationCompleted);
            }
            this.InvokeAsync("si_ActCreateTel_ob", new object[] {
                        mt_Dyn_ActCreateTel_req}, this.si_ActCreateTel_obOperationCompleted, userState);
        }
        
        private void Onsi_ActCreateTel_obOperationCompleted(object arg) {
            if ((this.si_ActCreateTel_obCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_ActCreateTel_obCompleted(this, new si_ActCreateTel_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_ActCreateTel_req {
        
        private string tYPEField;
        
        private string mOB_NUMBERField;
        
        private string oBJECT_IDField;
        
        private string pROCESS_TYPEField;
        
        private string aCCOUNT_IDField;
        
        private string pOSTING_DATEField;
        
        //private bool pOSTING_DATEFieldSpecified;
        
        private string pOINT_TYPEField;
        
        private decimal pOINTSField;
        
        //private bool pOINTSFieldSpecified;
        
        private string cAMPAIGN_HE_IDField;
        
        private string sOURCE_SYSTEMField;
        
        private string lOYALTY_BRANDField;
        
        private string vGROUPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOB_NUMBER {
            get {
                return this.mOB_NUMBERField;
            }
            set {
                this.mOB_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBJECT_ID {
            get {
                return this.oBJECT_IDField;
            }
            set {
                this.oBJECT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROCESS_TYPE {
            get {
                return this.pROCESS_TYPEField;
            }
            set {
                this.pROCESS_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSTING_DATE {
            get {
                return this.pOSTING_DATEField;
            }
            set {
                this.pOSTING_DATEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool POSTING_DATESpecified {
        //    get {
        //        return this.pOSTING_DATEFieldSpecified;
        //    }
        //    set {
        //        this.pOSTING_DATEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POINT_TYPE {
            get {
                return this.pOINT_TYPEField;
            }
            set {
                this.pOINT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal POINTS {
            get {
                return this.pOINTSField;
            }
            set {
                this.pOINTSField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool POINTSSpecified {
        //    get {
        //        return this.pOINTSFieldSpecified;
        //    }
        //    set {
        //        this.pOINTSFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAMPAIGN_HE_ID {
            get {
                return this.cAMPAIGN_HE_IDField;
            }
            set {
                this.cAMPAIGN_HE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM {
            get {
                return this.sOURCE_SYSTEMField;
            }
            set {
                this.sOURCE_SYSTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND {
            get {
                return this.lOYALTY_BRANDField;
            }
            set {
                this.lOYALTY_BRANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP {
            get {
                return this.vGROUPField;
            }
            set {
                this.vGROUPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_ActCreateTel_res {
        
        private dt_Dyn_ActCreateTel_resItem[] i_ZCRMT047_dynField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_Dyn_ActCreateTel_resItem[] I_ZCRMT047_dyn {
            get {
                return this.i_ZCRMT047_dynField;
            }
            set {
                this.i_ZCRMT047_dynField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_ActCreateTel_resItem {
        
        private string oBJECT_IDField;
        
        private string pROCESS_TYPEField;
        
        private string cHECK_FLAGField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBJECT_ID {
            get {
                return this.oBJECT_IDField;
            }
            set {
                this.oBJECT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROCESS_TYPE {
            get {
                return this.pROCESS_TYPEField;
            }
            set {
                this.pROCESS_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHECK_FLAG {
            get {
                return this.cHECK_FLAGField;
            }
            set {
                this.cHECK_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_ActCreateTel_obCompletedEventHandler(object sender, si_ActCreateTel_obCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_ActCreateTel_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal si_ActCreateTel_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_Dyn_ActCreateTel_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_ActCreateTel_res)(this.results[0]));
            }
        }
    }
}
