//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace HmjNew.Service
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_Dyn_DispMemQuick_obBinding", Namespace="http://jahwa.com/pos/crm")]
    public partial class si_Dyn_DispMemQuick_obService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_Dyn_DispMemQuick_obOperationCompleted;
        
        /// <remarks/>
        public si_Dyn_DispMemQuick_obService() {
            this.Url = ConfigurationManager.AppSettings["WebServerURL"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_DispMemQuick_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUser"],
            ConfigurationManager.AppSettings["WebServerPass"]);
        }
        
        /// <remarks/>
        public event si_Dyn_DispMemQuick_obCompletedEventHandler si_Dyn_DispMemQuick_obCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_DispMemQuick_res", Namespace="http://jahwa.com/pos/crm")]
        public dt_Dyn_DispMemQuick_res si_Dyn_DispMemQuick_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")]
        dt_Dyn_DispMemQuick_req mt_Dyn_DispMemQuick_req) {
            object[] results = this.Invoke("si_Dyn_DispMemQuick_ob", new object[] {
                        mt_Dyn_DispMemQuick_req});
            return ((dt_Dyn_DispMemQuick_res)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsi_Dyn_DispMemQuick_ob(dt_Dyn_DispMemQuick_req mt_Dyn_DispMemQuick_req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("si_Dyn_DispMemQuick_ob", new object[] {
                        mt_Dyn_DispMemQuick_req}, callback, asyncState);
        }
        
        /// <remarks/>
        public dt_Dyn_DispMemQuick_res Endsi_Dyn_DispMemQuick_ob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_DispMemQuick_res)(results[0]));
        }
        
        /// <remarks/>
        public void si_Dyn_DispMemQuick_obAsync(dt_Dyn_DispMemQuick_req mt_Dyn_DispMemQuick_req) {
            this.si_Dyn_DispMemQuick_obAsync(mt_Dyn_DispMemQuick_req, null);
        }
        
        /// <remarks/>
        public void si_Dyn_DispMemQuick_obAsync(dt_Dyn_DispMemQuick_req mt_Dyn_DispMemQuick_req, object userState) {
            if ((this.si_Dyn_DispMemQuick_obOperationCompleted == null)) {
                this.si_Dyn_DispMemQuick_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_Dyn_DispMemQuick_obOperationCompleted);
            }
            this.InvokeAsync("si_Dyn_DispMemQuick_ob", new object[] {
                        mt_Dyn_DispMemQuick_req}, this.si_Dyn_DispMemQuick_obOperationCompleted, userState);
        }
        
        private void Onsi_Dyn_DispMemQuick_obOperationCompleted(object arg) {
            if ((this.si_Dyn_DispMemQuick_obCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_Dyn_DispMemQuick_obCompleted(this, new si_Dyn_DispMemQuick_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_DispMemQuick_req {
        
        private string dATA_SOURCEField;
        
        private string aCCOUNT_IDField;
        
        private string mOB_NUMBERField;
        
        private string bpField;
        
        private string vGROUPField;
        
        private string lOYALTY_BRANDField;
        
        private string sOURCE_SYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE {
            get {
                return this.dATA_SOURCEField;
            }
            set {
                this.dATA_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOB_NUMBER {
            get {
                return this.mOB_NUMBERField;
            }
            set {
                this.mOB_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BP {
            get {
                return this.bpField;
            }
            set {
                this.bpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP {
            get {
                return this.vGROUPField;
            }
            set {
                this.vGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND {
            get {
                return this.lOYALTY_BRANDField;
            }
            set {
                this.lOYALTY_BRANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM {
            get {
                return this.sOURCE_SYSTEMField;
            }
            set {
                this.sOURCE_SYSTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_DispMemQuick_res {
        
        private string zTYPEField;
        
        private string mESSAGEField;
        
        private dt_Dyn_DispMemQuick_resITEM[] i_ZCRMT316Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTYPE {
            get {
                return this.zTYPEField;
            }
            set {
                this.zTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_Dyn_DispMemQuick_resITEM[] I_ZCRMT316 {
            get {
                return this.i_ZCRMT316Field;
            }
            set {
                this.i_ZCRMT316Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_DispMemQuick_resITEM {
        
        private string dATA_SOURCEField;
        
        private string aCCOUNT_IDField;
        
        private string nAME_LASTField;
        
        private string nAME_FIRSTField;
        
        private string nAME_TField;
        
        private string xSEXField;
        
        private string bIRTHDTField;
        
        //private bool bIRTHDTFieldSpecified;
        
        private string mOB_NUMBERField;
        
        private string rEG_DATEField;
        
        //private bool rEG_DATEFieldSpecified;
        
        private string pARTNERField;
        
        private string dEPTIDField;
        
        private string dEPT_TField;
        
        private string zZAFLD000004Field;
        
        private string zZAFLD000004_TField;
        
        private string zTIERField;
        
        private string iF_TRANSFORMField;
        
        private string iF_HMJField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE {
            get {
                return this.dATA_SOURCEField;
            }
            set {
                this.dATA_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME_LAST {
            get {
                return this.nAME_LASTField;
            }
            set {
                this.nAME_LASTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME_FIRST {
            get {
                return this.nAME_FIRSTField;
            }
            set {
                this.nAME_FIRSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME_T {
            get {
                return this.nAME_TField;
            }
            set {
                this.nAME_TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XSEX {
            get {
                return this.xSEXField;
            }
            set {
                this.xSEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIRTHDT {
            get {
                return this.bIRTHDTField;
            }
            set {
                this.bIRTHDTField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool BIRTHDTSpecified {
        //    get {
        //        return this.bIRTHDTFieldSpecified;
        //    }
        //    set {
        //        this.bIRTHDTFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOB_NUMBER {
            get {
                return this.mOB_NUMBERField;
            }
            set {
                this.mOB_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REG_DATE {
            get {
                return this.rEG_DATEField;
            }
            set {
                this.rEG_DATEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool REG_DATESpecified {
        //    get {
        //        return this.rEG_DATEFieldSpecified;
        //    }
        //    set {
        //        this.rEG_DATEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARTNER {
            get {
                return this.pARTNERField;
            }
            set {
                this.pARTNERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPTID {
            get {
                return this.dEPTIDField;
            }
            set {
                this.dEPTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPT_T {
            get {
                return this.dEPT_TField;
            }
            set {
                this.dEPT_TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZAFLD000004 {
            get {
                return this.zZAFLD000004Field;
            }
            set {
                this.zZAFLD000004Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZAFLD000004_T {
            get {
                return this.zZAFLD000004_TField;
            }
            set {
                this.zZAFLD000004_TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTIER {
            get {
                return this.zTIERField;
            }
            set {
                this.zTIERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IF_TRANSFORM {
            get {
                return this.iF_TRANSFORMField;
            }
            set {
                this.iF_TRANSFORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IF_HMJ {
            get {
                return this.iF_HMJField;
            }
            set {
                this.iF_HMJField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_Dyn_DispMemQuick_obCompletedEventHandler(object sender, si_Dyn_DispMemQuick_obCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_Dyn_DispMemQuick_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal si_Dyn_DispMemQuick_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_Dyn_DispMemQuick_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_DispMemQuick_res)(this.results[0]));
            }
        }
    }
}
