//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace HmjNew.Service
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "si_Dyn_QueryMemberShipBinding_obBinding", Namespace = "http://jahwa.com/pos/crm")]
    public partial class si_Dyn_QueryMemberShipBinding_obService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback si_Dyn_QueryMemberShipBinding_obOperationCompleted;

        /// <remarks/>
        public si_Dyn_QueryMemberShipBinding_obService()
        {
            this.Url = ConfigurationManager.AppSettings["WebServerURL"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_QueryMemberShipBinding_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUser"],
            ConfigurationManager.AppSettings["WebServerPass"]);
        }

        /// <remarks/>
        public event si_Dyn_QueryMemberShipBinding_obCompletedEventHandler si_Dyn_QueryMemberShipBinding_obCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_QueryMemberShipBinding_res", Namespace = "http://jahwa.com/pos/crm")]
        public dt_Dyn_QueryMemberShipBinding_res si_Dyn_QueryMemberShipBinding_ob([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://jahwa.com/pos/crm")] dt_Dyn_QueryMemberShipBinding_req mt_Dyn_QueryMemberShipBinding_req)
        {
            object[] results = this.Invoke("si_Dyn_QueryMemberShipBinding_ob", new object[] {
                        mt_Dyn_QueryMemberShipBinding_req});
            return ((dt_Dyn_QueryMemberShipBinding_res)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginsi_Dyn_QueryMemberShipBinding_ob(dt_Dyn_QueryMemberShipBinding_req mt_Dyn_QueryMemberShipBinding_req, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("si_Dyn_QueryMemberShipBinding_ob", new object[] {
                        mt_Dyn_QueryMemberShipBinding_req}, callback, asyncState);
        }

        /// <remarks/>
        public dt_Dyn_QueryMemberShipBinding_res Endsi_Dyn_QueryMemberShipBinding_ob(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_QueryMemberShipBinding_res)(results[0]));
        }

        /// <remarks/>
        public void si_Dyn_QueryMemberShipBinding_obAsync(dt_Dyn_QueryMemberShipBinding_req mt_Dyn_QueryMemberShipBinding_req)
        {
            this.si_Dyn_QueryMemberShipBinding_obAsync(mt_Dyn_QueryMemberShipBinding_req, null);
        }

        /// <remarks/>
        public void si_Dyn_QueryMemberShipBinding_obAsync(dt_Dyn_QueryMemberShipBinding_req mt_Dyn_QueryMemberShipBinding_req, object userState)
        {
            if ((this.si_Dyn_QueryMemberShipBinding_obOperationCompleted == null))
            {
                this.si_Dyn_QueryMemberShipBinding_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_Dyn_QueryMemberShipBinding_obOperationCompleted);
            }
            this.InvokeAsync("si_Dyn_QueryMemberShipBinding_ob", new object[] {
                        mt_Dyn_QueryMemberShipBinding_req}, this.si_Dyn_QueryMemberShipBinding_obOperationCompleted, userState);
        }

        private void Onsi_Dyn_QueryMemberShipBinding_obOperationCompleted(object arg)
        {
            if ((this.si_Dyn_QueryMemberShipBinding_obCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_Dyn_QueryMemberShipBinding_obCompleted(this, new si_Dyn_QueryMemberShipBinding_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_QueryMemberShipBinding_req
    {

        private string vGROUPField;

        private string dATA_SOURCEField;

        private string sOURCE_SYSTEMField;

        private string lOYALTY_BRANDField;

        private string mOB_NUMBERField;

        private dt_Dyn_QueryMemberShipBinding_reqITEM[] bRANDLISTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP
        {
            get
            {
                return this.vGROUPField;
            }
            set
            {
                this.vGROUPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE
        {
            get
            {
                return this.dATA_SOURCEField;
            }
            set
            {
                this.dATA_SOURCEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM
        {
            get
            {
                return this.sOURCE_SYSTEMField;
            }
            set
            {
                this.sOURCE_SYSTEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND
        {
            get
            {
                return this.lOYALTY_BRANDField;
            }
            set
            {
                this.lOYALTY_BRANDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOB_NUMBER
        {
            get
            {
                return this.mOB_NUMBERField;
            }
            set
            {
                this.mOB_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public dt_Dyn_QueryMemberShipBinding_reqITEM[] BRANDLIST
        {
            get
            {
                return this.bRANDLISTField;
            }
            set
            {
                this.bRANDLISTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_QueryMemberShipBinding_reqITEM
    {

        private string vGROUP2Field;

        private string dATA_SOURCE2Field;

        private string lOYALTY_BRAND2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP2
        {
            get
            {
                return this.vGROUP2Field;
            }
            set
            {
                this.vGROUP2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE2
        {
            get
            {
                return this.dATA_SOURCE2Field;
            }
            set
            {
                this.dATA_SOURCE2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND2
        {
            get
            {
                return this.lOYALTY_BRAND2Field;
            }
            set
            {
                this.lOYALTY_BRAND2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_QueryMemberShipBinding_res
    {

        private string zRETURNField;

        private string mESSAGEField;

        private dt_Dyn_QueryMemberShipBinding_resITEM[] bRANDLISTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRETURN
        {
            get
            {
                return this.zRETURNField;
            }
            set
            {
                this.zRETURNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public dt_Dyn_QueryMemberShipBinding_resITEM[] BRANDLIST
        {
            get
            {
                return this.bRANDLISTField;
            }
            set
            {
                this.bRANDLISTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_QueryMemberShipBinding_resITEM
    {

        private string vGROUP2Field;

        private string dATA_SOURCE2Field;

        private string lOYALTY_BRAND2Field;

        private string mEMBER_ID2Field;

        private string mOB_NUMBER2Field;

        private string iF_BINDINGField;

        private decimal pOINT_AVAILABLEField;

        private string tIER_CODEField;

        private string tIER_DESCField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP2
        {
            get
            {
                return this.vGROUP2Field;
            }
            set
            {
                this.vGROUP2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE2
        {
            get
            {
                return this.dATA_SOURCE2Field;
            }
            set
            {
                this.dATA_SOURCE2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND2
        {
            get
            {
                return this.lOYALTY_BRAND2Field;
            }
            set
            {
                this.lOYALTY_BRAND2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMBER_ID2
        {
            get
            {
                return this.mEMBER_ID2Field;
            }
            set
            {
                this.mEMBER_ID2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOB_NUMBER2
        {
            get
            {
                return this.mOB_NUMBER2Field;
            }
            set
            {
                this.mOB_NUMBER2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IF_BINDING
        {
            get
            {
                return this.iF_BINDINGField;
            }
            set
            {
                this.iF_BINDINGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal POINT_AVAILABLE
        {
            get
            {
                return this.pOINT_AVAILABLEField;
            }
            set
            {
                this.pOINT_AVAILABLEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIER_CODE
        {
            get
            {
                return this.tIER_CODEField;
            }
            set
            {
                this.tIER_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIER_DESC
        {
            get
            {
                return this.tIER_DESCField;
            }
            set
            {
                this.tIER_DESCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_Dyn_QueryMemberShipBinding_obCompletedEventHandler(object sender, si_Dyn_QueryMemberShipBinding_obCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_Dyn_QueryMemberShipBinding_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal si_Dyn_QueryMemberShipBinding_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public dt_Dyn_QueryMemberShipBinding_res Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_QueryMemberShipBinding_res)(this.results[0]));
            }
        }
    }
}
