
//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Text;

using SPACRM.Entity.ORMapping;

namespace SPACRM.Entity
{

	[TableName("CardApiTicket")]
	public partial class CardApiTicket : BaseEntity
	{
		private int _Id;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int Id
		{ get{ return _Id; } 	set{ _Id = value ; } }
		private string _Cardapi_Ticket;
		/// <summary>
		/// 
		///  nvarchar(500)
		/// </summary>
		[Nullable  ] 
		public string Cardapi_Ticket
		{ get{ return _Cardapi_Ticket; } 	set{ _Cardapi_Ticket = value ;  OnPropertyChanged("Cardapi_Ticket"); } }
		private DateTime? _GetTicketTime;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? GetTicketTime
		{ get{ return _GetTicketTime; } 	set{ _GetTicketTime = value ;  OnPropertyChanged("GetTicketTime"); } }
	}

	[TableName("Cust_Old_New")]
	public partial class Cust_Old_New : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _FromUserName;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string FromUserName
		{ get{ return _FromUserName; } 	set{ _FromUserName = value ;  OnPropertyChanged("FromUserName"); } }
		private string _ToUserName;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string ToUserName
		{ get{ return _ToUserName; } 	set{ _ToUserName = value ;  OnPropertyChanged("ToUserName"); } }
		private string _ToUserNickName;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string ToUserNickName
		{ get{ return _ToUserNickName; } 	set{ _ToUserNickName = value ;  OnPropertyChanged("ToUserNickName"); } }
		private DateTime? _CreateTime;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? CreateTime
		{ get{ return _CreateTime; } 	set{ _CreateTime = value ;  OnPropertyChanged("CreateTime"); } }
		private int? _OrderID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? OrderID
		{ get{ return _OrderID; } 	set{ _OrderID = value ;  OnPropertyChanged("OrderID"); } }
		private int? _Price;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Price
		{ get{ return _Price; } 	set{ _Price = value ;  OnPropertyChanged("Price"); } }
		private int? _State;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? State
		{ get{ return _State; } 	set{ _State = value ;  OnPropertyChanged("State"); } }
		private int? _RandNum;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? RandNum
		{ get{ return _RandNum; } 	set{ _RandNum = value ;  OnPropertyChanged("RandNum"); } }
		private int? _Jie;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Jie
		{ get{ return _Jie; } 	set{ _Jie = value ;  OnPropertyChanged("Jie"); } }
	}

	[TableName("OAauth_Log")]
	public partial class OAauth_Log : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _FromUserName;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string FromUserName
		{ get{ return _FromUserName; } 	set{ _FromUserName = value ;  OnPropertyChanged("FromUserName"); } }
		private string _ToUserName;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string ToUserName
		{ get{ return _ToUserName; } 	set{ _ToUserName = value ;  OnPropertyChanged("ToUserName"); } }
		private string _Nickname;
		/// <summary>
		/// 
		///  nvarchar(80)
		/// </summary>
		[Nullable  ] 
		public string Nickname
		{ get{ return _Nickname; } 	set{ _Nickname = value ;  OnPropertyChanged("Nickname"); } }
		private string _headimgurl;
		/// <summary>
		/// 
		///  varchar(250)
		/// </summary>
		[Nullable  ] 
		public string headimgurl
		{ get{ return _headimgurl; } 	set{ _headimgurl = value ;  OnPropertyChanged("headimgurl"); } }
		private DateTime? _CreateDate;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? CreateDate
		{ get{ return _CreateDate; } 	set{ _CreateDate = value ;  OnPropertyChanged("CreateDate"); } }
		private string _MobilePhone;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string MobilePhone
		{ get{ return _MobilePhone; } 	set{ _MobilePhone = value ;  OnPropertyChanged("MobilePhone"); } }
		private string _sex;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string sex
		{ get{ return _sex; } 	set{ _sex = value ;  OnPropertyChanged("sex"); } }
		private string _province;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string province
		{ get{ return _province; } 	set{ _province = value ;  OnPropertyChanged("province"); } }
		private string _city;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string city
		{ get{ return _city; } 	set{ _city = value ;  OnPropertyChanged("city"); } }
		private string _country;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string country
		{ get{ return _country; } 	set{ _country = value ;  OnPropertyChanged("country"); } }
		private string _DownPic;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string DownPic
		{ get{ return _DownPic; } 	set{ _DownPic = value ;  OnPropertyChanged("DownPic"); } }
		private string _Phone;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string Phone
		{ get{ return _Phone; } 	set{ _Phone = value ;  OnPropertyChanged("Phone"); } }
		private DateTime? _BangTime;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? BangTime
		{ get{ return _BangTime; } 	set{ _BangTime = value ;  OnPropertyChanged("BangTime"); } }
		private decimal? _TotalMoney;
		/// <summary>
		/// 
		///  decimal(18,2)
		/// </summary>
		[Nullable  ] 
		public decimal? TotalMoney
		{ get{ return _TotalMoney; } 	set{ _TotalMoney = value ;  OnPropertyChanged("TotalMoney"); } }
		private decimal? _SurplusMoney;
		/// <summary>
		/// 
		///  decimal(18,2)
		/// </summary>
		[Nullable  ] 
		public decimal? SurplusMoney
		{ get{ return _SurplusMoney; } 	set{ _SurplusMoney = value ;  OnPropertyChanged("SurplusMoney"); } }
		private string _Ticket;
		/// <summary>
		/// 
		///  varchar(250)
		/// </summary>
		[Nullable  ] 
		public string Ticket
		{ get{ return _Ticket; } 	set{ _Ticket = value ;  OnPropertyChanged("Ticket"); } }
		private string _MEDIA_ID;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string MEDIA_ID
		{ get{ return _MEDIA_ID; } 	set{ _MEDIA_ID = value ;  OnPropertyChanged("MEDIA_ID"); } }
		private DateTime? _MEDIA_Time;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? MEDIA_Time
		{ get{ return _MEDIA_Time; } 	set{ _MEDIA_Time = value ;  OnPropertyChanged("MEDIA_Time"); } }
		private string _SeaImg;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string SeaImg
		{ get{ return _SeaImg; } 	set{ _SeaImg = value ;  OnPropertyChanged("SeaImg"); } }
		private int? _SeaSource;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? SeaSource
		{ get{ return _SeaSource; } 	set{ _SeaSource = value ;  OnPropertyChanged("SeaSource"); } }
	}

	[TableName("ORG_INFO")]
	public partial class ORG_INFO : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _ORG_NO;
		/// <summary>
		/// 
		///  varchar(64)
		/// </summary>

		public string ORG_NO
		{ get{ return _ORG_NO; } 	set{ _ORG_NO = value ;  OnPropertyChanged("ORG_NO"); } }
		private string _ORG_NAME;
		/// <summary>
		/// 
		///  varchar(64)
		/// </summary>

		public string ORG_NAME
		{ get{ return _ORG_NAME; } 	set{ _ORG_NAME = value ;  OnPropertyChanged("ORG_NAME"); } }
		private string _PROVINCE;
		/// <summary>
		/// 
		///  varchar(64)
		/// </summary>
		[Nullable  ] 
		public string PROVINCE
		{ get{ return _PROVINCE; } 	set{ _PROVINCE = value ;  OnPropertyChanged("PROVINCE"); } }
		private string _CITY;
		/// <summary>
		/// 
		///  varchar(64)
		/// </summary>
		[Nullable  ] 
		public string CITY
		{ get{ return _CITY; } 	set{ _CITY = value ;  OnPropertyChanged("CITY"); } }
		private string _ADDRESS;
		/// <summary>
		/// 
		///  varchar(256)
		/// </summary>
		[Nullable  ] 
		public string ADDRESS
		{ get{ return _ADDRESS; } 	set{ _ADDRESS = value ;  OnPropertyChanged("ADDRESS"); } }
		private string _TELEPHONE;
		/// <summary>
		/// 
		///  varchar(32)
		/// </summary>
		[Nullable  ] 
		public string TELEPHONE
		{ get{ return _TELEPHONE; } 	set{ _TELEPHONE = value ;  OnPropertyChanged("TELEPHONE"); } }
		private string _FAX;
		/// <summary>
		/// 
		///  varchar(32)
		/// </summary>
		[Nullable  ] 
		public string FAX
		{ get{ return _FAX; } 	set{ _FAX = value ;  OnPropertyChanged("FAX"); } }
		private string _CONTACT;
		/// <summary>
		/// 
		///  varchar(64)
		/// </summary>
		[Nullable  ] 
		public string CONTACT
		{ get{ return _CONTACT; } 	set{ _CONTACT = value ;  OnPropertyChanged("CONTACT"); } }
		private int _STATUS;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>

		public int STATUS
		{ get{ return _STATUS; } 	set{ _STATUS = value ;  OnPropertyChanged("STATUS"); } }
		private string _REMARK;
		/// <summary>
		/// 
		///  varchar(256)
		/// </summary>
		[Nullable  ] 
		public string REMARK
		{ get{ return _REMARK; } 	set{ _REMARK = value ;  OnPropertyChanged("REMARK"); } }
		private string _ToUserName;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string ToUserName
		{ get{ return _ToUserName; } 	set{ _ToUserName = value ;  OnPropertyChanged("ToUserName"); } }
		private string _AppID;
		/// <summary>
		/// 
		///  varchar(100)
		/// </summary>
		[Nullable  ] 
		public string AppID
		{ get{ return _AppID; } 	set{ _AppID = value ;  OnPropertyChanged("AppID"); } }
		private string _Appsecret;
		/// <summary>
		/// 
		///  varchar(100)
		/// </summary>
		[Nullable  ] 
		public string Appsecret
		{ get{ return _Appsecret; } 	set{ _Appsecret = value ;  OnPropertyChanged("Appsecret"); } }
		private string _Access_token;
		/// <summary>
		/// 
		///  varchar(250)
		/// </summary>
		[Nullable  ] 
		public string Access_token
		{ get{ return _Access_token; } 	set{ _Access_token = value ;  OnPropertyChanged("Access_token"); } }
		private string _OneOpenID;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string OneOpenID
		{ get{ return _OneOpenID; } 	set{ _OneOpenID = value ;  OnPropertyChanged("OneOpenID"); } }
		private string _JSapi_Ticket;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string JSapi_Ticket
		{ get{ return _JSapi_Ticket; } 	set{ _JSapi_Ticket = value ;  OnPropertyChanged("JSapi_Ticket"); } }
		private DateTime? _GetTicketTime;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? GetTicketTime
		{ get{ return _GetTicketTime; } 	set{ _GetTicketTime = value ;  OnPropertyChanged("GetTicketTime"); } }
		private int? _LOGO_PIC;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? LOGO_PIC
		{ get{ return _LOGO_PIC; } 	set{ _LOGO_PIC = value ;  OnPropertyChanged("LOGO_PIC"); } }
	}

	[TableName("tb_log")]
	public partial class Tb_log : BaseEntity
	{
		private long _id;
		/// <summary>
		/// 
		///  bigint(19)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public long id
		{ get{ return _id; } 	set{ _id = value ; } }
		private string _title;
		/// <summary>
		/// 
		///  nvarchar(50)
		/// </summary>

		public string title
		{ get{ return _title; } 	set{ _title = value ;  OnPropertyChanged("title"); } }
		private string _msgType;
		/// <summary>
		/// 
		///  nvarchar(20)
		/// </summary>
		[Nullable  ] 
		public string msgType
		{ get{ return _msgType; } 	set{ _msgType = value ;  OnPropertyChanged("msgType"); } }
		private string _msgContent;
		/// <summary>
		/// 
		///  text(2147483647)
		/// </summary>
		[Nullable  ] 
		public string msgContent
		{ get{ return _msgContent; } 	set{ _msgContent = value ;  OnPropertyChanged("msgContent"); } }
		private DateTime? _createDate;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? createDate
		{ get{ return _createDate; } 	set{ _createDate = value ;  OnPropertyChanged("createDate"); } }
	}

	[TableName("WD_TemplateMessageLog")]
	public partial class WD_TemplateMessageLog : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _FromUserName;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string FromUserName
		{ get{ return _FromUserName; } 	set{ _FromUserName = value ;  OnPropertyChanged("FromUserName"); } }
		private string _First;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string First
		{ get{ return _First; } 	set{ _First = value ;  OnPropertyChanged("First"); } }
		private string _keyword;
		/// <summary>
		/// 
		///  text(2147483647)
		/// </summary>
		[Nullable  ] 
		public string keyword
		{ get{ return _keyword; } 	set{ _keyword = value ;  OnPropertyChanged("keyword"); } }
		private string _url;
		/// <summary>
		/// 
		///  varchar(350)
		/// </summary>
		[Nullable  ] 
		public string url
		{ get{ return _url; } 	set{ _url = value ;  OnPropertyChanged("url"); } }
		private string _remark;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string remark
		{ get{ return _remark; } 	set{ _remark = value ;  OnPropertyChanged("remark"); } }
		private DateTime? _CreateDate;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? CreateDate
		{ get{ return _CreateDate; } 	set{ _CreateDate = value ;  OnPropertyChanged("CreateDate"); } }
		private string _Result;
		/// <summary>
		/// 
		///  varchar(350)
		/// </summary>
		[Nullable  ] 
		public string Result
		{ get{ return _Result; } 	set{ _Result = value ;  OnPropertyChanged("Result"); } }
	}

	[TableName("WXCouponGiveInfo")]
	public partial class WXCouponGiveInfo : BaseEntity
	{
		private long _Id;
		/// <summary>
		/// 
		///  bigint(19)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public long Id
		{ get{ return _Id; } 	set{ _Id = value ; } }
		private string _Openid;
		/// <summary>
		/// 
		///  nvarchar(150)
		/// </summary>

		public string Openid
		{ get{ return _Openid; } 	set{ _Openid = value ;  OnPropertyChanged("Openid"); } }
		private string _Mobile;
		/// <summary>
		/// 
		///  nvarchar(20)
		/// </summary>

		public string Mobile
		{ get{ return _Mobile; } 	set{ _Mobile = value ;  OnPropertyChanged("Mobile"); } }
		private int _GetCoupon;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>

		public int GetCoupon
		{ get{ return _GetCoupon; } 	set{ _GetCoupon = value ;  OnPropertyChanged("GetCoupon"); } }
		private string _CouponNo;
		/// <summary>
		/// 
		///  nvarchar(150)
		/// </summary>
		[Nullable  ] 
		public string CouponNo
		{ get{ return _CouponNo; } 	set{ _CouponNo = value ;  OnPropertyChanged("CouponNo"); } }
		private int? _Status;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Status
		{ get{ return _Status; } 	set{ _Status = value ;  OnPropertyChanged("Status"); } }
		private string _CardId;
		/// <summary>
		/// 
		///  nvarchar(200)
		/// </summary>
		[Nullable  ] 
		public string CardId
		{ get{ return _CardId; } 	set{ _CardId = value ;  OnPropertyChanged("CardId"); } }
		private DateTime _CreateDate;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>

		public DateTime CreateDate
		{ get{ return _CreateDate; } 	set{ _CreateDate = value ;  OnPropertyChanged("CreateDate"); } }
		private DateTime? _CouponGetDate;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? CouponGetDate
		{ get{ return _CouponGetDate; } 	set{ _CouponGetDate = value ;  OnPropertyChanged("CouponGetDate"); } }
		private DateTime? _UseDate;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? UseDate
		{ get{ return _UseDate; } 	set{ _UseDate = value ;  OnPropertyChanged("UseDate"); } }
		private string _UseStoreCode;
		/// <summary>
		/// 
		///  nvarchar(100)
		/// </summary>
		[Nullable  ] 
		public string UseStoreCode
		{ get{ return _UseStoreCode; } 	set{ _UseStoreCode = value ;  OnPropertyChanged("UseStoreCode"); } }
	}

	[TableName("WXCouponNoInfo")]
	public partial class WXCouponNoInfo : BaseEntity
	{
		private long _id;
		/// <summary>
		/// 
		///  bigint(19)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public long id
		{ get{ return _id; } 	set{ _id = value ; } }
		private string _CouponNo;
		/// <summary>
		/// 
		///  nvarchar(50)
		/// </summary>

		public string CouponNo
		{ get{ return _CouponNo; } 	set{ _CouponNo = value ;  OnPropertyChanged("CouponNo"); } }
		private bool _IsImport;
		/// <summary>
		/// 
		///  bit
		/// </summary>

		public bool IsImport
		{ get{ return _IsImport; } 	set{ _IsImport = value ;  OnPropertyChanged("IsImport"); } }
		private DateTime? _ImportDate;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? ImportDate
		{ get{ return _ImportDate; } 	set{ _ImportDate = value ;  OnPropertyChanged("ImportDate"); } }
	}

	[TableName("WXCUST_FANS")]
	public partial class WXCUST_FANS : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _NAME;
		/// <summary>
		/// 
		///  nvarchar(80)
		/// </summary>
		[Nullable  ] 
		public string NAME
		{ get{ return _NAME; } 	set{ _NAME = value ;  OnPropertyChanged("NAME"); } }
		private bool? _GENDER;
		/// <summary>
		/// 
		///  bit
		/// </summary>
		[Nullable  ] 
		public bool? GENDER
		{ get{ return _GENDER; } 	set{ _GENDER = value ;  OnPropertyChanged("GENDER"); } }
		private string _COUNTRY;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string COUNTRY
		{ get{ return _COUNTRY; } 	set{ _COUNTRY = value ;  OnPropertyChanged("COUNTRY"); } }
		private string _PROVINCE;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string PROVINCE
		{ get{ return _PROVINCE; } 	set{ _PROVINCE = value ;  OnPropertyChanged("PROVINCE"); } }
		private string _CITY;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string CITY
		{ get{ return _CITY; } 	set{ _CITY = value ;  OnPropertyChanged("CITY"); } }
		private string _FROMUSERNAME;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string FROMUSERNAME
		{ get{ return _FROMUSERNAME; } 	set{ _FROMUSERNAME = value ;  OnPropertyChanged("FROMUSERNAME"); } }
		private string _ToUserName;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string ToUserName
		{ get{ return _ToUserName; } 	set{ _ToUserName = value ;  OnPropertyChanged("ToUserName"); } }
		private string _IMAGE;
		/// <summary>
		/// 
		///  varchar(256)
		/// </summary>
		[Nullable  ] 
		public string IMAGE
		{ get{ return _IMAGE; } 	set{ _IMAGE = value ;  OnPropertyChanged("IMAGE"); } }
		private int? _TOTAL_OPPR;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? TOTAL_OPPR
		{ get{ return _TOTAL_OPPR; } 	set{ _TOTAL_OPPR = value ;  OnPropertyChanged("TOTAL_OPPR"); } }
		private int? _AVAL_OPPR;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? AVAL_OPPR
		{ get{ return _AVAL_OPPR; } 	set{ _AVAL_OPPR = value ;  OnPropertyChanged("AVAL_OPPR"); } }
		private string _UNIN_CODE;
		/// <summary>
		/// 
		///  varchar(10)
		/// </summary>
		[Nullable  ] 
		public string UNIN_CODE
		{ get{ return _UNIN_CODE; } 	set{ _UNIN_CODE = value ;  OnPropertyChanged("UNIN_CODE"); } }
		private string _REFE_CODE;
		/// <summary>
		/// 
		///  varchar(10)
		/// </summary>
		[Nullable  ] 
		public string REFE_CODE
		{ get{ return _REFE_CODE; } 	set{ _REFE_CODE = value ;  OnPropertyChanged("REFE_CODE"); } }
		private int? _STATUS;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? STATUS
		{ get{ return _STATUS; } 	set{ _STATUS = value ;  OnPropertyChanged("STATUS"); } }
		private string _REMARK;
		/// <summary>
		/// 
		///  varchar(500)
		/// </summary>
		[Nullable  ] 
		public string REMARK
		{ get{ return _REMARK; } 	set{ _REMARK = value ;  OnPropertyChanged("REMARK"); } }
		private DateTime? _NOTICE_DATE;
		/// <summary>
		/// 
		///  date
		/// </summary>
		[Nullable  ] 
		public DateTime? NOTICE_DATE
		{ get{ return _NOTICE_DATE; } 	set{ _NOTICE_DATE = value ;  OnPropertyChanged("NOTICE_DATE"); } }
		private DateTime? _CANCEL_DATE;
		/// <summary>
		/// 
		///  date
		/// </summary>
		[Nullable  ] 
		public DateTime? CANCEL_DATE
		{ get{ return _CANCEL_DATE; } 	set{ _CANCEL_DATE = value ;  OnPropertyChanged("CANCEL_DATE"); } }
		private DateTime? _LAST_CONN_DATE;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? LAST_CONN_DATE
		{ get{ return _LAST_CONN_DATE; } 	set{ _LAST_CONN_DATE = value ;  OnPropertyChanged("LAST_CONN_DATE"); } }
		private int? _LAST_LINK_QTY;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? LAST_LINK_QTY
		{ get{ return _LAST_LINK_QTY; } 	set{ _LAST_LINK_QTY = value ;  OnPropertyChanged("LAST_LINK_QTY"); } }
		private int? _TOTAL_CONN_QFTY;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? TOTAL_CONN_QFTY
		{ get{ return _TOTAL_CONN_QFTY; } 	set{ _TOTAL_CONN_QFTY = value ;  OnPropertyChanged("TOTAL_CONN_QFTY"); } }
		private DateTime? _CREATE_DATE;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? CREATE_DATE
		{ get{ return _CREATE_DATE; } 	set{ _CREATE_DATE = value ;  OnPropertyChanged("CREATE_DATE"); } }
		private string _CREATE_USER;
		/// <summary>
		/// 
		///  varchar(20)
		/// </summary>
		[Nullable  ] 
		public string CREATE_USER
		{ get{ return _CREATE_USER; } 	set{ _CREATE_USER = value ;  OnPropertyChanged("CREATE_USER"); } }
		private DateTime? _LAST_MODI_DATE;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? LAST_MODI_DATE
		{ get{ return _LAST_MODI_DATE; } 	set{ _LAST_MODI_DATE = value ;  OnPropertyChanged("LAST_MODI_DATE"); } }
		private string _LAST_MODI_USER;
		/// <summary>
		/// 
		///  varchar(20)
		/// </summary>
		[Nullable  ] 
		public string LAST_MODI_USER
		{ get{ return _LAST_MODI_USER; } 	set{ _LAST_MODI_USER = value ;  OnPropertyChanged("LAST_MODI_USER"); } }
	}

	[TableName("WXCUST_MSG_HIS")]
	public partial class WXCUST_MSG_HIS : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _TOUSERNAME;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string TOUSERNAME
		{ get{ return _TOUSERNAME; } 	set{ _TOUSERNAME = value ;  OnPropertyChanged("TOUSERNAME"); } }
		private int? _TO_FANSID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? TO_FANSID
		{ get{ return _TO_FANSID; } 	set{ _TO_FANSID = value ;  OnPropertyChanged("TO_FANSID"); } }
		private string _FROMUSERNAME;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string FROMUSERNAME
		{ get{ return _FROMUSERNAME; } 	set{ _FROMUSERNAME = value ;  OnPropertyChanged("FROMUSERNAME"); } }
		private int? _FROM_FANSID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? FROM_FANSID
		{ get{ return _FROM_FANSID; } 	set{ _FROM_FANSID = value ;  OnPropertyChanged("FROM_FANSID"); } }
		private string _MSGTYPE;
		/// <summary>
		/// 
		///  varchar(250)
		/// </summary>
		[Nullable  ] 
		public string MSGTYPE
		{ get{ return _MSGTYPE; } 	set{ _MSGTYPE = value ;  OnPropertyChanged("MSGTYPE"); } }
		private string _CONTENT;
		/// <summary>
		/// 
		///  varchar(-1)
		/// </summary>
		[Nullable  ] 
		public string CONTENT
		{ get{ return _CONTENT; } 	set{ _CONTENT = value ;  OnPropertyChanged("CONTENT"); } }
		private string _MSGID;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string MSGID
		{ get{ return _MSGID; } 	set{ _MSGID = value ;  OnPropertyChanged("MSGID"); } }
		private string _WXEVENT;
		/// <summary>
		/// 
		///  varchar(250)
		/// </summary>
		[Nullable  ] 
		public string WXEVENT
		{ get{ return _WXEVENT; } 	set{ _WXEVENT = value ;  OnPropertyChanged("WXEVENT"); } }
		private string _EVENTKEY;
		/// <summary>
		/// 
		///  varchar(250)
		/// </summary>
		[Nullable  ] 
		public string EVENTKEY
		{ get{ return _EVENTKEY; } 	set{ _EVENTKEY = value ;  OnPropertyChanged("EVENTKEY"); } }
		private string _LOCATION_X;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string LOCATION_X
		{ get{ return _LOCATION_X; } 	set{ _LOCATION_X = value ;  OnPropertyChanged("LOCATION_X"); } }
		private string _LOCATION_Y;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string LOCATION_Y
		{ get{ return _LOCATION_Y; } 	set{ _LOCATION_Y = value ;  OnPropertyChanged("LOCATION_Y"); } }
		private string _SCALE;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string SCALE
		{ get{ return _SCALE; } 	set{ _SCALE = value ;  OnPropertyChanged("SCALE"); } }
		private string _LABEL;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string LABEL
		{ get{ return _LABEL; } 	set{ _LABEL = value ;  OnPropertyChanged("LABEL"); } }
		private string _PICURL;
		/// <summary>
		/// 
		///  varchar(350)
		/// </summary>
		[Nullable  ] 
		public string PICURL
		{ get{ return _PICURL; } 	set{ _PICURL = value ;  OnPropertyChanged("PICURL"); } }
		private string _VEDIOURL;
		/// <summary>
		/// 
		///  varchar(350)
		/// </summary>
		[Nullable  ] 
		public string VEDIOURL
		{ get{ return _VEDIOURL; } 	set{ _VEDIOURL = value ;  OnPropertyChanged("VEDIOURL"); } }
		private string _RESXML;
		/// <summary>
		/// 
		///  text(2147483647)
		/// </summary>
		[Nullable  ] 
		public string RESXML
		{ get{ return _RESXML; } 	set{ _RESXML = value ;  OnPropertyChanged("RESXML"); } }
		private int? _ReturnID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? ReturnID
		{ get{ return _ReturnID; } 	set{ _ReturnID = value ;  OnPropertyChanged("ReturnID"); } }
		private string _Return_Con;
		/// <summary>
		/// 
		///  text(2147483647)
		/// </summary>
		[Nullable  ] 
		public string Return_Con
		{ get{ return _Return_Con; } 	set{ _Return_Con = value ;  OnPropertyChanged("Return_Con"); } }
		private bool? _IS_RETURN;
		/// <summary>
		/// 
		///  bit
		/// </summary>
		[Nullable  ] 
		public bool? IS_RETURN
		{ get{ return _IS_RETURN; } 	set{ _IS_RETURN = value ;  OnPropertyChanged("IS_RETURN"); } }
		private bool? _IS_STAR;
		/// <summary>
		/// 
		///  bit
		/// </summary>
		[Nullable  ] 
		public bool? IS_STAR
		{ get{ return _IS_STAR; } 	set{ _IS_STAR = value ;  OnPropertyChanged("IS_STAR"); } }
		private string _STATUS;
		/// <summary>
		/// 
		///  varchar(20)
		/// </summary>
		[Nullable  ] 
		public string STATUS
		{ get{ return _STATUS; } 	set{ _STATUS = value ;  OnPropertyChanged("STATUS"); } }
		private DateTime? _CREATE_DATE;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? CREATE_DATE
		{ get{ return _CREATE_DATE; } 	set{ _CREATE_DATE = value ;  OnPropertyChanged("CREATE_DATE"); } }
	}

	[TableName("WXCustomMenu")]
	public partial class WXCustomMenu : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _Name;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string Name
		{ get{ return _Name; } 	set{ _Name = value ;  OnPropertyChanged("Name"); } }
		private int? _Type;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Type
		{ get{ return _Type; } 	set{ _Type = value ;  OnPropertyChanged("Type"); } }
		private int? _ParentID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? ParentID
		{ get{ return _ParentID; } 	set{ _ParentID = value ;  OnPropertyChanged("ParentID"); } }
		private string _Content;
		/// <summary>
		/// 
		///  varchar(500)
		/// </summary>
		[Nullable  ] 
		public string Content
		{ get{ return _Content; } 	set{ _Content = value ;  OnPropertyChanged("Content"); } }
		private int? _Graphic_ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Graphic_ID
		{ get{ return _Graphic_ID; } 	set{ _Graphic_ID = value ;  OnPropertyChanged("Graphic_ID"); } }
		private string _Url;
		/// <summary>
		/// 
		///  varchar(500)
		/// </summary>
		[Nullable  ] 
		public string Url
		{ get{ return _Url; } 	set{ _Url = value ;  OnPropertyChanged("Url"); } }
		private int _Depth;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>

		public int Depth
		{ get{ return _Depth; } 	set{ _Depth = value ;  OnPropertyChanged("Depth"); } }
		private int? _OrderNum;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? OrderNum
		{ get{ return _OrderNum; } 	set{ _OrderNum = value ;  OnPropertyChanged("OrderNum"); } }
		private int _Merchants_ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>

		public int Merchants_ID
		{ get{ return _Merchants_ID; } 	set{ _Merchants_ID = value ;  OnPropertyChanged("Merchants_ID"); } }
		private DateTime _CeateTime;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>

		public DateTime CeateTime
		{ get{ return _CeateTime; } 	set{ _CeateTime = value ;  OnPropertyChanged("CeateTime"); } }
		private DateTime _LastUpdateTime;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>

		public DateTime LastUpdateTime
		{ get{ return _LastUpdateTime; } 	set{ _LastUpdateTime = value ;  OnPropertyChanged("LastUpdateTime"); } }
	}

	[TableName("WXGraphicDetail")]
	public partial class WXGraphicDetail : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _Title;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string Title
		{ get{ return _Title; } 	set{ _Title = value ;  OnPropertyChanged("Title"); } }
		private string _Describe;
		/// <summary>
		/// 
		///  varchar(250)
		/// </summary>
		[Nullable  ] 
		public string Describe
		{ get{ return _Describe; } 	set{ _Describe = value ;  OnPropertyChanged("Describe"); } }
		private string _Pic;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string Pic
		{ get{ return _Pic; } 	set{ _Pic = value ;  OnPropertyChanged("Pic"); } }
		private bool? _IsURL;
		/// <summary>
		/// 
		///  bit
		/// </summary>
		[Nullable  ] 
		public bool? IsURL
		{ get{ return _IsURL; } 	set{ _IsURL = value ;  OnPropertyChanged("IsURL"); } }
		private string _URL;
		/// <summary>
		/// 
		///  varchar(150)
		/// </summary>
		[Nullable  ] 
		public string URL
		{ get{ return _URL; } 	set{ _URL = value ;  OnPropertyChanged("URL"); } }
		private string _Body;
		/// <summary>
		/// 
		///  text(2147483647)
		/// </summary>
		[Nullable  ] 
		public string Body
		{ get{ return _Body; } 	set{ _Body = value ;  OnPropertyChanged("Body"); } }
		private int? _Sorting;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Sorting
		{ get{ return _Sorting; } 	set{ _Sorting = value ;  OnPropertyChanged("Sorting"); } }
		private int? _List_ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? List_ID
		{ get{ return _List_ID; } 	set{ _List_ID = value ;  OnPropertyChanged("List_ID"); } }
		private string _Author;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string Author
		{ get{ return _Author; } 	set{ _Author = value ;  OnPropertyChanged("Author"); } }
	}

	[TableName("WXGraphicList")]
	public partial class WXGraphicList : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _Title;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string Title
		{ get{ return _Title; } 	set{ _Title = value ;  OnPropertyChanged("Title"); } }
		private int? _Merchants_ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Merchants_ID
		{ get{ return _Merchants_ID; } 	set{ _Merchants_ID = value ;  OnPropertyChanged("Merchants_ID"); } }
		private DateTime? _CreateDate;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? CreateDate
		{ get{ return _CreateDate; } 	set{ _CreateDate = value ;  OnPropertyChanged("CreateDate"); } }
	}

	[TableName("WXInformation")]
	public partial class WXInformation : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private string _CreateTime;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string CreateTime
		{ get{ return _CreateTime; } 	set{ _CreateTime = value ;  OnPropertyChanged("CreateTime"); } }
		private string _MsgType;
		/// <summary>
		/// 
		///  varchar(50)
		/// </summary>
		[Nullable  ] 
		public string MsgType
		{ get{ return _MsgType; } 	set{ _MsgType = value ;  OnPropertyChanged("MsgType"); } }
		private string _Content;
		/// <summary>
		/// 
		///  varchar(500)
		/// </summary>
		[Nullable  ] 
		public string Content
		{ get{ return _Content; } 	set{ _Content = value ;  OnPropertyChanged("Content"); } }
		private int? _replyType;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? replyType
		{ get{ return _replyType; } 	set{ _replyType = value ;  OnPropertyChanged("replyType"); } }
		private string _KeyWords;
		/// <summary>
		/// 
		///  varchar(350)
		/// </summary>
		[Nullable  ] 
		public string KeyWords
		{ get{ return _KeyWords; } 	set{ _KeyWords = value ;  OnPropertyChanged("KeyWords"); } }
		private int? _Merchants_ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Merchants_ID
		{ get{ return _Merchants_ID; } 	set{ _Merchants_ID = value ;  OnPropertyChanged("Merchants_ID"); } }
		private int? _Graphic_ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? Graphic_ID
		{ get{ return _Graphic_ID; } 	set{ _Graphic_ID = value ;  OnPropertyChanged("Graphic_ID"); } }
		private int? _MatchingType;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Nullable  ] 
		public int? MatchingType
		{ get{ return _MatchingType; } 	set{ _MatchingType = value ;  OnPropertyChanged("MatchingType"); } }
	}

	[TableName("WXLOG")]
	public partial class WXLOG : BaseEntity
	{
		private int _ID;
		/// <summary>
		/// 
		///  int(10)
		/// </summary>
		[Identity, PrimaryKey(1)] 
		public int ID
		{ get{ return _ID; } 	set{ _ID = value ; } }
		private DateTime? _TIME;
		/// <summary>
		/// 
		///  datetime(3)
		/// </summary>
		[Nullable  ] 
		public DateTime? TIME
		{ get{ return _TIME; } 	set{ _TIME = value ;  OnPropertyChanged("TIME"); } }
		private string _CON;
		/// <summary>
		/// 
		///  varchar(8000)
		/// </summary>
		[Nullable  ] 
		public string CON
		{ get{ return _CON; } 	set{ _CON = value ;  OnPropertyChanged("CON"); } }
	}
}
