//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace Hmj.WebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_Dyn_GetPointDetail_obBinding", Namespace="http://jahwa.com/pos/crm")]
    public partial class si_Dyn_GetPointDetail_obService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_Dyn_GetPointDetail_obOperationCompleted;
        
        /// <remarks/>
        public si_Dyn_GetPointDetail_obService() {
            this.Url = ConfigurationManager.AppSettings["WebServerURLTest"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_GetPointDetail_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUserTest"],
            ConfigurationManager.AppSettings["WebServerPassTest"]);
        }
        
        /// <remarks/>
        public event si_Dyn_GetPointDetail_obCompletedEventHandler si_Dyn_GetPointDetail_obCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_GetPointDetail_res", Namespace="http://jahwa.com/pos/crm")]
        public dt_Dyn_GetPointDetail_res si_Dyn_GetPointDetail_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")]
        dt_Dyn_GetPointDetail_req mt_Dyn_GetPointDetail_req) {
            object[] results = this.Invoke("si_Dyn_GetPointDetail_ob", new object[] {
                        mt_Dyn_GetPointDetail_req});
            return ((dt_Dyn_GetPointDetail_res)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsi_Dyn_GetPointDetail_ob(dt_Dyn_GetPointDetail_req mt_Dyn_GetPointDetail_req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("si_Dyn_GetPointDetail_ob", new object[] {
                        mt_Dyn_GetPointDetail_req}, callback, asyncState);
        }
        
        /// <remarks/>
        public dt_Dyn_GetPointDetail_res Endsi_Dyn_GetPointDetail_ob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_GetPointDetail_res)(results[0]));
        }
        
        /// <remarks/>
        public void si_Dyn_GetPointDetail_obAsync(dt_Dyn_GetPointDetail_req mt_Dyn_GetPointDetail_req) {
            this.si_Dyn_GetPointDetail_obAsync(mt_Dyn_GetPointDetail_req, null);
        }
        
        /// <remarks/>
        public void si_Dyn_GetPointDetail_obAsync(dt_Dyn_GetPointDetail_req mt_Dyn_GetPointDetail_req, object userState) {
            if ((this.si_Dyn_GetPointDetail_obOperationCompleted == null)) {
                this.si_Dyn_GetPointDetail_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_Dyn_GetPointDetail_obOperationCompleted);
            }
            this.InvokeAsync("si_Dyn_GetPointDetail_ob", new object[] {
                        mt_Dyn_GetPointDetail_req}, this.si_Dyn_GetPointDetail_obOperationCompleted, userState);
        }
        
        private void Onsi_Dyn_GetPointDetail_obOperationCompleted(object arg) {
            if ((this.si_Dyn_GetPointDetail_obCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_Dyn_GetPointDetail_obCompleted(this, new si_Dyn_GetPointDetail_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_GetPointDetail_req {
        
        private string pOINT_TYPEField;
        
        private string aCCOUNT_IDField;
        
        private string zEND_DATEField;
        
        //private bool zEND_DATEFieldSpecified;
        
        private string zSTART_DATEField;
        
        //private bool zSTART_DATEFieldSpecified;
        
        private string sOURCE_SYSTEMField;
        
        private string lOYALTY_BRANDField;
        
        private string vGROUPField;
        
        private string dATA_SOURCEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POINT_TYPE {
            get {
                return this.pOINT_TYPEField;
            }
            set {
                this.pOINT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEND_DATE {
            get {
                return this.zEND_DATEField;
            }
            set {
                this.zEND_DATEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool ZEND_DATESpecified {
        //    get {
        //        return this.zEND_DATEFieldSpecified;
        //    }
        //    set {
        //        this.zEND_DATEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZSTART_DATE {
            get {
                return this.zSTART_DATEField;
            }
            set {
                this.zSTART_DATEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool ZSTART_DATESpecified {
        //    get {
        //        return this.zSTART_DATEFieldSpecified;
        //    }
        //    set {
        //        this.zSTART_DATEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM {
            get {
                return this.sOURCE_SYSTEMField;
            }
            set {
                this.sOURCE_SYSTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND {
            get {
                return this.lOYALTY_BRANDField;
            }
            set {
                this.lOYALTY_BRANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP {
            get {
                return this.vGROUPField;
            }
            set {
                this.vGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE {
            get {
                return this.dATA_SOURCEField;
            }
            set {
                this.dATA_SOURCEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class ZCRMT402_Dyn {
        
        private string aCCOUNT_IDField;
        
        private string cREATED_TIMEField;
        
        //private bool cREATED_TIMEFieldSpecified;
        
        private string oRDER_TYPEField;
        
        private string sAPORDER_IDField;
        
        private string sAPITEM_IDField;
        
        private string wB_ORDER_IDField;
        
        private string iTEM_IDField;
        
        private decimal pOINTSField;
        
        //private bool pOINTSFieldSpecified;
        
        private string pRODUCT_IDField;
        
        private string pRODUCT_DESCField;
        
        private string cATEGORYField;
        
        private decimal qUANTITYField;
        
        //private bool qUANTITYFieldSpecified;
        
        private string qTY_UNITField;
        
        private string eXPIRE_DATEField;
        
        private bool eXPIRE_DATEFieldSpecified;
        
        private string cZ_BAField;
        
        private string cZ_MDField;
        
        private string pOINT_CODEField;
        
        private string pOINT_RULEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATED_TIME {
            get {
                return this.cREATED_TIMEField;
            }
            set {
                this.cREATED_TIMEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool CREATED_TIMESpecified {
        //    get {
        //        return this.cREATED_TIMEFieldSpecified;
        //    }
        //    set {
        //        this.cREATED_TIMEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORDER_TYPE {
            get {
                return this.oRDER_TYPEField;
            }
            set {
                this.oRDER_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAPORDER_ID {
            get {
                return this.sAPORDER_IDField;
            }
            set {
                this.sAPORDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAPITEM_ID {
            get {
                return this.sAPITEM_IDField;
            }
            set {
                this.sAPITEM_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WB_ORDER_ID {
            get {
                return this.wB_ORDER_IDField;
            }
            set {
                this.wB_ORDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_ID {
            get {
                return this.iTEM_IDField;
            }
            set {
                this.iTEM_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal POINTS {
            get {
                return this.pOINTSField;
            }
            set {
                this.pOINTSField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool POINTSSpecified {
        //    get {
        //        return this.pOINTSFieldSpecified;
        //    }
        //    set {
        //        this.pOINTSFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCT_ID {
            get {
                return this.pRODUCT_IDField;
            }
            set {
                this.pRODUCT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCT_DESC {
            get {
                return this.pRODUCT_DESCField;
            }
            set {
                this.pRODUCT_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CATEGORY {
            get {
                return this.cATEGORYField;
            }
            set {
                this.cATEGORYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool QUANTITYSpecified {
        //    get {
        //        return this.qUANTITYFieldSpecified;
        //    }
        //    set {
        //        this.qUANTITYFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY_UNIT {
            get {
                return this.qTY_UNITField;
            }
            set {
                this.qTY_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXPIRE_DATE {
            get {
                return this.eXPIRE_DATEField;
            }
            set {
                this.eXPIRE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EXPIRE_DATESpecified {
            get {
                return this.eXPIRE_DATEFieldSpecified;
            }
            set {
                this.eXPIRE_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CZ_BA {
            get {
                return this.cZ_BAField;
            }
            set {
                this.cZ_BAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CZ_MD {
            get {
                return this.cZ_MDField;
            }
            set {
                this.cZ_MDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POINT_CODE {
            get {
                return this.pOINT_CODEField;
            }
            set {
                this.pOINT_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POINT_RULE {
            get {
                return this.pOINT_RULEField;
            }
            set {
                this.pOINT_RULEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_GetPointDetail_res {
        
        private ZCRMT402_Dyn[] zCRMT402Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCRMT402_Dyn[] ZCRMT402 {
            get {
                return this.zCRMT402Field;
            }
            set {
                this.zCRMT402Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_Dyn_GetPointDetail_obCompletedEventHandler(object sender, si_Dyn_GetPointDetail_obCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_Dyn_GetPointDetail_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal si_Dyn_GetPointDetail_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_Dyn_GetPointDetail_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_GetPointDetail_res)(this.results[0]));
            }
        }
    }
}
