//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace Hmj.WebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_Dyn_ChangePassword_obBinding", Namespace="http://jahwa.com/pos/crm")]
    public partial class si_Dyn_ChangePassword_obService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_Dyn_ChangePassword_obOperationCompleted;
        
        /// <remarks/>
        public si_Dyn_ChangePassword_obService() {
            this.Url = ConfigurationManager.AppSettings["WebServerURL"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_ChangePassword_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUser"],
            ConfigurationManager.AppSettings["WebServerPass"]);
        }
        
        /// <remarks/>
        public event si_Dyn_ChangePassword_obCompletedEventHandler si_Dyn_ChangePassword_obCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_ChangePassword_res", Namespace="http://jahwa.com/pos/crm")]
        public dt_Dyn_ChangePassword_res si_Dyn_ChangePassword_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")] dt_Dyn_ChangePassword_req mt_Dyn_ChangePassword_req) {
            object[] results = this.Invoke("si_Dyn_ChangePassword_ob", new object[] {
                        mt_Dyn_ChangePassword_req});
            return ((dt_Dyn_ChangePassword_res)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsi_Dyn_ChangePassword_ob(dt_Dyn_ChangePassword_req mt_Dyn_ChangePassword_req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("si_Dyn_ChangePassword_ob", new object[] {
                        mt_Dyn_ChangePassword_req}, callback, asyncState);
        }
        
        /// <remarks/>
        public dt_Dyn_ChangePassword_res Endsi_Dyn_ChangePassword_ob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_ChangePassword_res)(results[0]));
        }
        
        /// <remarks/>
        public void si_Dyn_ChangePassword_obAsync(dt_Dyn_ChangePassword_req mt_Dyn_ChangePassword_req) {
            this.si_Dyn_ChangePassword_obAsync(mt_Dyn_ChangePassword_req, null);
        }
        
        /// <remarks/>
        public void si_Dyn_ChangePassword_obAsync(dt_Dyn_ChangePassword_req mt_Dyn_ChangePassword_req, object userState) {
            if ((this.si_Dyn_ChangePassword_obOperationCompleted == null)) {
                this.si_Dyn_ChangePassword_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_Dyn_ChangePassword_obOperationCompleted);
            }
            this.InvokeAsync("si_Dyn_ChangePassword_ob", new object[] {
                        mt_Dyn_ChangePassword_req}, this.si_Dyn_ChangePassword_obOperationCompleted, userState);
        }
        
        private void Onsi_Dyn_ChangePassword_obOperationCompleted(object arg) {
            if ((this.si_Dyn_ChangePassword_obCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_Dyn_ChangePassword_obCompleted(this, new si_Dyn_ChangePassword_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_ChangePassword_req {
        
        private string dATA_SOURCEField;
        
        private string zVTWEGField;
        
        private string aCCOUNT_IDField;
        
        private string eXCHANGEPASSField;
        
        private string eXCHANGEPASS2Field;
        
        private string iNIT_FLAGField;
        
        private string pASS_TYPEField;
        
        private string rEASONField;
        
        private string sOURCE_SYSTEMField;
        
        private string lOYALTY_BRANDField;
        
        private string vGROUPField;
        
        private string mEMBER_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE {
            get {
                return this.dATA_SOURCEField;
            }
            set {
                this.dATA_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZVTWEG {
            get {
                return this.zVTWEGField;
            }
            set {
                this.zVTWEGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXCHANGEPASS {
            get {
                return this.eXCHANGEPASSField;
            }
            set {
                this.eXCHANGEPASSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXCHANGEPASS2 {
            get {
                return this.eXCHANGEPASS2Field;
            }
            set {
                this.eXCHANGEPASS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INIT_FLAG {
            get {
                return this.iNIT_FLAGField;
            }
            set {
                this.iNIT_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASS_TYPE {
            get {
                return this.pASS_TYPEField;
            }
            set {
                this.pASS_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REASON {
            get {
                return this.rEASONField;
            }
            set {
                this.rEASONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM {
            get {
                return this.sOURCE_SYSTEMField;
            }
            set {
                this.sOURCE_SYSTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND {
            get {
                return this.lOYALTY_BRANDField;
            }
            set {
                this.lOYALTY_BRANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP {
            get {
                return this.vGROUPField;
            }
            set {
                this.vGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMBER_ID {
            get {
                return this.mEMBER_IDField;
            }
            set {
                this.mEMBER_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_ChangePassword_res {
        
        private string zRETURNField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRETURN {
            get {
                return this.zRETURNField;
            }
            set {
                this.zRETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_Dyn_ChangePassword_obCompletedEventHandler(object sender, si_Dyn_ChangePassword_obCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_Dyn_ChangePassword_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal si_Dyn_ChangePassword_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_Dyn_ChangePassword_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_ChangePassword_res)(this.results[0]));
            }
        }
    }
}
