//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     会员实时修改接口
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace Hmj.WebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;
    using System.Web.Script.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "si_Dyn_UpdateMemberShip_obBinding", Namespace = "http://jahwa.com/pos/crm")]
    public partial class si_Dyn_UpdateMemberShip_obService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback si_Dyn_UpdateMemberShip_obOperationCompleted;

        /// <remarks/>
        public si_Dyn_UpdateMemberShip_obService()
        {
            this.Url = ConfigurationManager.AppSettings["WebServerURLTest"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_UpdateMemberShip_ob";
            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUserTest"],
            ConfigurationManager.AppSettings["WebServerPassTest"]);

        }

        /// <remarks/>
        public event si_Dyn_UpdateMemberShip_obCompletedEventHandler si_Dyn_UpdateMemberShip_obCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_UpdateMemberShip_res", Namespace = "http://jahwa.com/pos/crm")]
        public dt_Dyn_UpdateMemberShip_res si_Dyn_UpdateMemberShip_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")]
        dt_Dyn_UpdateMemberShip_req mt_Dyn_UpdateMemberShip_req)
        {

            object[] results = this.Invoke("si_Dyn_UpdateMemberShip_ob", new object[] {
                        mt_Dyn_UpdateMemberShip_req});


            return ((dt_Dyn_UpdateMemberShip_res)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginsi_Dyn_UpdateMemberShip_ob(dt_Dyn_UpdateMemberShip_req mt_Dyn_UpdateMemberShip_req, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("si_Dyn_UpdateMemberShip_ob", new object[] {
                        mt_Dyn_UpdateMemberShip_req}, callback, asyncState);
        }

        /// <remarks/>
        public dt_Dyn_UpdateMemberShip_res Endsi_Dyn_UpdateMemberShip_ob(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_UpdateMemberShip_res)(results[0]));
        }

        /// <remarks/>
        public void si_Dyn_UpdateMemberShip_obAsync(dt_Dyn_UpdateMemberShip_req mt_Dyn_UpdateMemberShip_req)
        {
            this.si_Dyn_UpdateMemberShip_obAsync(mt_Dyn_UpdateMemberShip_req, null);
        }

        /// <remarks/>
        public void si_Dyn_UpdateMemberShip_obAsync(dt_Dyn_UpdateMemberShip_req mt_Dyn_UpdateMemberShip_req, object userState)
        {
            if ((this.si_Dyn_UpdateMemberShip_obOperationCompleted == null))
            {
                this.si_Dyn_UpdateMemberShip_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_Dyn_UpdateMemberShip_obOperationCompleted);
            }
            this.InvokeAsync("si_Dyn_UpdateMemberShip_ob", new object[] {
                        mt_Dyn_UpdateMemberShip_req}, this.si_Dyn_UpdateMemberShip_obOperationCompleted, userState);
        }

        private void Onsi_Dyn_UpdateMemberShip_obOperationCompleted(object arg)
        {
            if ((this.si_Dyn_UpdateMemberShip_obCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_Dyn_UpdateMemberShip_obCompleted(this, new si_Dyn_UpdateMemberShip_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_UpdateMemberShip_req
    {

        private ZCRMT322_Dyn[] zCRMT316Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ZCRMT322_Dyn[] ZCRMT316
        {
            get
            {
                return this.zCRMT316Field;
            }
            set
            {
                this.zCRMT316Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://jahwa.com/pos/crm")]
    public partial class ZCRMT322_Dyn
    {

        private string dATA_SOURCEField;

        private string aCCOUNT_IDField;

        private string nAME_LASTField;

        private string nAME_FIRSTField;

        private string nAME1_TEXTField;

        private string zTITLEField;

        private string nICKNAMEField;

        private string nAMEMIDDLEField;

        private string nAMCOUNTRYField;

        private string rEGIONField;

        private string tRANSPZONEField;

        private string xSEXField;

        private string bIRTHDTField;

        //private bool bIRTHDTFieldSpecified;

        private string jOBGRField;

        private string bUPA_IDTYPE_PRSField;

        private string iDNUMBERField;

        private string pSTREETField;

        private string cSTREETField;

        private string pOST_CODE1Field;

        private string cPOST_CODE1Field;

        private string tEL_NUMBERField;

        private string mOB_NUMBERField;

        private string sMTP_ADDRField;

        private string qqField;

        private string mSNField;

        private string cTEL_NUMBERField;

        private string cMOB_NUMBERField;

        private string cFAX_NUMBERField;

        private string cSMTP_ADDRField;

        private string rE_BPEXTField;

        private string rE_MOBILEField;

        private string rEG_DATEField;

        //private bool rEG_DATEFieldSpecified;

        private string lOGINNAMEField;

        private string lOGINPASSField;

        private string lOGINPASS2Field;

        private string dEPTIDField;

        private string eMPIDField;

        private string vGROUPField;

        private string dIS_CHANNELField;

        private string dIVISIONField;

        private string zC001Field;

        private string zC002Field;

        private string zC003Field;

        private string zC004Field;

        private string zC005Field;

        private string zC008Field;

        private string zC007Field;

        private string zA001Field;

        private string zA002Field;

        private string zA003Field;

        private string zA004Field;

        private string zA005Field;

        private string zA006Field;

        private string zB002Field;

        private string zB003Field;

        private string zC009Field;

        private string zC010Field;

        private string zC011Field;

        private string zC012Field;

        private string zC013Field;

        private string zC014Field;

        private string zC015Field;

        private string zC016Field;

        private string zC017Field;

        private string zC018Field;

        private string zC019Field;

        private string zC020Field;

        private string zC021Field;

        private string oPENIDField;

        private string lOYALTY_BRANDField;

        private string sOURCE_SYSTEMField;

        private string wECHATFOLLOWSTATUSField;

        private string wECHATNAMEField;

        private string wECHATVALIDField;

        private string pARTNERField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE
        {
            get
            {
                return this.dATA_SOURCEField;
            }
            set
            {
                this.dATA_SOURCEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID
        {
            get
            {
                return this.aCCOUNT_IDField;
            }
            set
            {
                this.aCCOUNT_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME_LAST
        {
            get
            {
                return this.nAME_LASTField;
            }
            set
            {
                this.nAME_LASTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME_FIRST
        {
            get
            {
                return this.nAME_FIRSTField;
            }
            set
            {
                this.nAME_FIRSTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1_TEXT
        {
            get
            {
                return this.nAME1_TEXTField;
            }
            set
            {
                this.nAME1_TEXTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTITLE
        {
            get
            {
                return this.zTITLEField;
            }
            set
            {
                this.zTITLEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NICKNAME
        {
            get
            {
                return this.nICKNAMEField;
            }
            set
            {
                this.nICKNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAMEMIDDLE
        {
            get
            {
                return this.nAMEMIDDLEField;
            }
            set
            {
                this.nAMEMIDDLEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAMCOUNTRY
        {
            get
            {
                return this.nAMCOUNTRYField;
            }
            set
            {
                this.nAMCOUNTRYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGION
        {
            get
            {
                return this.rEGIONField;
            }
            set
            {
                this.rEGIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSPZONE
        {
            get
            {
                return this.tRANSPZONEField;
            }
            set
            {
                this.tRANSPZONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XSEX
        {
            get
            {
                return this.xSEXField;
            }
            set
            {
                this.xSEXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIRTHDT
        {
            get
            {
                return this.bIRTHDTField;
            }
            set
            {
                this.bIRTHDTField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool BIRTHDTSpecified
        //{
        //    get
        //    {
        //        return this.bIRTHDTFieldSpecified;
        //    }
        //    set
        //    {
        //        this.bIRTHDTFieldSpecified = value;
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JOBGR
        {
            get
            {
                return this.jOBGRField;
            }
            set
            {
                this.jOBGRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUPA_IDTYPE_PRS
        {
            get
            {
                return this.bUPA_IDTYPE_PRSField;
            }
            set
            {
                this.bUPA_IDTYPE_PRSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDNUMBER
        {
            get
            {
                return this.iDNUMBERField;
            }
            set
            {
                this.iDNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSTREET
        {
            get
            {
                return this.pSTREETField;
            }
            set
            {
                this.pSTREETField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CSTREET
        {
            get
            {
                return this.cSTREETField;
            }
            set
            {
                this.cSTREETField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POST_CODE1
        {
            get
            {
                return this.pOST_CODE1Field;
            }
            set
            {
                this.pOST_CODE1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CPOST_CODE1
        {
            get
            {
                return this.cPOST_CODE1Field;
            }
            set
            {
                this.cPOST_CODE1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEL_NUMBER
        {
            get
            {
                return this.tEL_NUMBERField;
            }
            set
            {
                this.tEL_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOB_NUMBER
        {
            get
            {
                return this.mOB_NUMBERField;
            }
            set
            {
                this.mOB_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SMTP_ADDR
        {
            get
            {
                return this.sMTP_ADDRField;
            }
            set
            {
                this.sMTP_ADDRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QQ
        {
            get
            {
                return this.qqField;
            }
            set
            {
                this.qqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSN
        {
            get
            {
                return this.mSNField;
            }
            set
            {
                this.mSNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CTEL_NUMBER
        {
            get
            {
                return this.cTEL_NUMBERField;
            }
            set
            {
                this.cTEL_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CMOB_NUMBER
        {
            get
            {
                return this.cMOB_NUMBERField;
            }
            set
            {
                this.cMOB_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CFAX_NUMBER
        {
            get
            {
                return this.cFAX_NUMBERField;
            }
            set
            {
                this.cFAX_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CSMTP_ADDR
        {
            get
            {
                return this.cSMTP_ADDRField;
            }
            set
            {
                this.cSMTP_ADDRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RE_BPEXT
        {
            get
            {
                return this.rE_BPEXTField;
            }
            set
            {
                this.rE_BPEXTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RE_MOBILE
        {
            get
            {
                return this.rE_MOBILEField;
            }
            set
            {
                this.rE_MOBILEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REG_DATE
        {
            get
            {
                return this.rEG_DATEField;
            }
            set
            {
                this.rEG_DATEField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool REG_DATESpecified
        //{
        //    get
        //    {
        //        return this.rEG_DATEFieldSpecified;
        //    }
        //    set
        //    {
        //        this.rEG_DATEFieldSpecified = value;
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGINNAME
        {
            get
            {
                return this.lOGINNAMEField;
            }
            set
            {
                this.lOGINNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGINPASS
        {
            get
            {
                return this.lOGINPASSField;
            }
            set
            {
                this.lOGINPASSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGINPASS2
        {
            get
            {
                return this.lOGINPASS2Field;
            }
            set
            {
                this.lOGINPASS2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPTID
        {
            get
            {
                return this.dEPTIDField;
            }
            set
            {
                this.dEPTIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPID
        {
            get
            {
                return this.eMPIDField;
            }
            set
            {
                this.eMPIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP
        {
            get
            {
                return this.vGROUPField;
            }
            set
            {
                this.vGROUPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIS_CHANNEL
        {
            get
            {
                return this.dIS_CHANNELField;
            }
            set
            {
                this.dIS_CHANNELField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIVISION
        {
            get
            {
                return this.dIVISIONField;
            }
            set
            {
                this.dIVISIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC001
        {
            get
            {
                return this.zC001Field;
            }
            set
            {
                this.zC001Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC002
        {
            get
            {
                return this.zC002Field;
            }
            set
            {
                this.zC002Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC003
        {
            get
            {
                return this.zC003Field;
            }
            set
            {
                this.zC003Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC004
        {
            get
            {
                return this.zC004Field;
            }
            set
            {
                this.zC004Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC005
        {
            get
            {
                return this.zC005Field;
            }
            set
            {
                this.zC005Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC008
        {
            get
            {
                return this.zC008Field;
            }
            set
            {
                this.zC008Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC007
        {
            get
            {
                return this.zC007Field;
            }
            set
            {
                this.zC007Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZA001
        {
            get
            {
                return this.zA001Field;
            }
            set
            {
                this.zA001Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZA002
        {
            get
            {
                return this.zA002Field;
            }
            set
            {
                this.zA002Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZA003
        {
            get
            {
                return this.zA003Field;
            }
            set
            {
                this.zA003Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZA004
        {
            get
            {
                return this.zA004Field;
            }
            set
            {
                this.zA004Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZA005
        {
            get
            {
                return this.zA005Field;
            }
            set
            {
                this.zA005Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZA006
        {
            get
            {
                return this.zA006Field;
            }
            set
            {
                this.zA006Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZB002
        {
            get
            {
                return this.zB002Field;
            }
            set
            {
                this.zB002Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZB003
        {
            get
            {
                return this.zB003Field;
            }
            set
            {
                this.zB003Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC009
        {
            get
            {
                return this.zC009Field;
            }
            set
            {
                this.zC009Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC010
        {
            get
            {
                return this.zC010Field;
            }
            set
            {
                this.zC010Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC011
        {
            get
            {
                return this.zC011Field;
            }
            set
            {
                this.zC011Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC012
        {
            get
            {
                return this.zC012Field;
            }
            set
            {
                this.zC012Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC013
        {
            get
            {
                return this.zC013Field;
            }
            set
            {
                this.zC013Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC014
        {
            get
            {
                return this.zC014Field;
            }
            set
            {
                this.zC014Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC015
        {
            get
            {
                return this.zC015Field;
            }
            set
            {
                this.zC015Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC016
        {
            get
            {
                return this.zC016Field;
            }
            set
            {
                this.zC016Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC017
        {
            get
            {
                return this.zC017Field;
            }
            set
            {
                this.zC017Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC018
        {
            get
            {
                return this.zC018Field;
            }
            set
            {
                this.zC018Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC019
        {
            get
            {
                return this.zC019Field;
            }
            set
            {
                this.zC019Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC020
        {
            get
            {
                return this.zC020Field;
            }
            set
            {
                this.zC020Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZC021
        {
            get
            {
                return this.zC021Field;
            }
            set
            {
                this.zC021Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPENID
        {
            get
            {
                return this.oPENIDField;
            }
            set
            {
                this.oPENIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND
        {
            get
            {
                return this.lOYALTY_BRANDField;
            }
            set
            {
                this.lOYALTY_BRANDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM
        {
            get
            {
                return this.sOURCE_SYSTEMField;
            }
            set
            {
                this.sOURCE_SYSTEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WECHATFOLLOWSTATUS
        {
            get
            {
                return this.wECHATFOLLOWSTATUSField;
            }
            set
            {
                this.wECHATFOLLOWSTATUSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WECHATNAME
        {
            get
            {
                return this.wECHATNAMEField;
            }
            set
            {
                this.wECHATNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WECHATVALID
        {
            get
            {
                return this.wECHATVALIDField;
            }
            set
            {
                this.wECHATVALIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARTNER
        {
            get
            {
                return this.pARTNERField;
            }
            set
            {
                this.pARTNERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_UpdateMemberShip_res
    {

        private string aCCOUNT_IDField;

        private string wV_MESSAGEField;

        private string wV_RETURNField;

        private string pARTNERField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID
        {
            get
            {
                return this.aCCOUNT_IDField;
            }
            set
            {
                this.aCCOUNT_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WV_MESSAGE
        {
            get
            {
                return this.wV_MESSAGEField;
            }
            set
            {
                this.wV_MESSAGEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WV_RETURN
        {
            get
            {
                return this.wV_RETURNField;
            }
            set
            {
                this.wV_RETURNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARTNER
        {
            get
            {
                return this.pARTNERField;
            }
            set
            {
                this.pARTNERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_Dyn_UpdateMemberShip_obCompletedEventHandler(object sender, si_Dyn_UpdateMemberShip_obCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_Dyn_UpdateMemberShip_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal si_Dyn_UpdateMemberShip_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public dt_Dyn_UpdateMemberShip_res Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_UpdateMemberShip_res)(this.results[0]));
            }
        }
    }
}
