//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace Hmj.WebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_Dyn_PosCpSearch_obBinding", Namespace="http://jahwa.com/pos/crm")]
    public partial class si_Dyn_PosCpSearch_obService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_PosCpSearch_obOperationCompleted;
        
        /// <remarks/>
        public si_Dyn_PosCpSearch_obService() {
            this.Url = ConfigurationManager.AppSettings["WebServerURL"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_PosCpSearch_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUser"],
            ConfigurationManager.AppSettings["WebServerPass"]);
        }
        
        /// <remarks/>
        public event si_PosCpSearch_obCompletedEventHandler si_PosCpSearch_obCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_PosCpSearch_res", Namespace="http://jahwa.com/pos/crm")]
        public dt_Dyn_PosCpSearch_res si_PosCpSearch_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")]
        dt_Dyn_PosCpSearch_req mt_Dyn_PosCpSearch_req) {
            object[] results = this.Invoke("si_PosCpSearch_ob", new object[] {
                        mt_Dyn_PosCpSearch_req});
            return ((dt_Dyn_PosCpSearch_res)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsi_PosCpSearch_ob(dt_Dyn_PosCpSearch_req mt_Dyn_PosCpSearch_req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("si_PosCpSearch_ob", new object[] {
                        mt_Dyn_PosCpSearch_req}, callback, asyncState);
        }
        
        /// <remarks/>
        public dt_Dyn_PosCpSearch_res Endsi_PosCpSearch_ob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_PosCpSearch_res)(results[0]));
        }
        
        /// <remarks/>
        public void si_PosCpSearch_obAsync(dt_Dyn_PosCpSearch_req mt_Dyn_PosCpSearch_req) {
            this.si_PosCpSearch_obAsync(mt_Dyn_PosCpSearch_req, null);
        }
        
        /// <remarks/>
        public void si_PosCpSearch_obAsync(dt_Dyn_PosCpSearch_req mt_Dyn_PosCpSearch_req, object userState) {
            if ((this.si_PosCpSearch_obOperationCompleted == null)) {
                this.si_PosCpSearch_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_PosCpSearch_obOperationCompleted);
            }
            this.InvokeAsync("si_PosCpSearch_ob", new object[] {
                        mt_Dyn_PosCpSearch_req}, this.si_PosCpSearch_obOperationCompleted, userState);
        }
        
        private void Onsi_PosCpSearch_obOperationCompleted(object arg) {
            if ((this.si_PosCpSearch_obCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_PosCpSearch_obCompleted(this, new si_PosCpSearch_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_PosCpSearch_req {
        
        private string aCCOUNT_IDField;
        
        private string mOB_NUMBERField;
        
        private string dATA_SOURCEField;
        
        private string vGROUPField;
        
        private string sOURCE_SYSTEMField;
        
        private string lOYALTY_BRANDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOB_NUMBER {
            get {
                return this.mOB_NUMBERField;
            }
            set {
                this.mOB_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE {
            get {
                return this.dATA_SOURCEField;
            }
            set {
                this.dATA_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP {
            get {
                return this.vGROUPField;
            }
            set {
                this.vGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM {
            get {
                return this.sOURCE_SYSTEMField;
            }
            set {
                this.sOURCE_SYSTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND {
            get {
                return this.lOYALTY_BRANDField;
            }
            set {
                this.lOYALTY_BRANDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class ZPARTERN_CP2 {
        
        private string bPEXTField;
        
        private string zCP_TYPEField;
        
        private string zCP_NUMField;
        
        private string zCP_PASSWField;
        
        private string zCP_USE_FLAGField;
        
        private string zCPUDATEField;
        
        //private bool zCPUDATEFieldSpecified;
        
        private string zCPSDATEField;
        
        //private bool zCPSDATEFieldSpecified;
        
        private string wB_ORDER_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPEXT {
            get {
                return this.bPEXTField;
            }
            set {
                this.bPEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_TYPE {
            get {
                return this.zCP_TYPEField;
            }
            set {
                this.zCP_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_NUM {
            get {
                return this.zCP_NUMField;
            }
            set {
                this.zCP_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_PASSW {
            get {
                return this.zCP_PASSWField;
            }
            set {
                this.zCP_PASSWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_USE_FLAG {
            get {
                return this.zCP_USE_FLAGField;
            }
            set {
                this.zCP_USE_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCPUDATE {
            get {
                return this.zCPUDATEField;
            }
            set {
                this.zCPUDATEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool ZCPUDATESpecified {
        //    get {
        //        return this.zCPUDATEFieldSpecified;
        //    }
        //    set {
        //        this.zCPUDATEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCPSDATE {
            get {
                return this.zCPSDATEField;
            }
            set {
                this.zCPSDATEField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool ZCPSDATESpecified {
        //    get {
        //        return this.zCPSDATEFieldSpecified;
        //    }
        //    set {
        //        this.zCPSDATEFieldSpecified = value;
        //    }
        //}
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WB_ORDER_ID {
            get {
                return this.wB_ORDER_IDField;
            }
            set {
                this.wB_ORDER_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class ZPARTERN_CP1 {
        
        private string bPEXTField;
        
        private string zCP_TYPEField;
        
        private string tOTALField;
        
        private string tOTAL_YSYField;
        
        private string tOTAL_WSYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPEXT {
            get {
                return this.bPEXTField;
            }
            set {
                this.bPEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_TYPE {
            get {
                return this.zCP_TYPEField;
            }
            set {
                this.zCP_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTAL_YSY {
            get {
                return this.tOTAL_YSYField;
            }
            set {
                this.tOTAL_YSYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTAL_WSY {
            get {
                return this.tOTAL_WSYField;
            }
            set {
                this.tOTAL_WSYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_PosCpSearch_res {
        
        private string zTYPEField;
        
        private string mESSAGEField;
        
        private ZPARTERN_CP1[] zPARTERN_CP1Field;
        
        private ZPARTERN_CP2[] zPARTERN_CP2Field;
        
        private dt_Dyn_PosCpSearch_resITEM[] zCPQ_RESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTYPE {
            get {
                return this.zTYPEField;
            }
            set {
                this.zTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPARTERN_CP1[] ZPARTERN_CP1 {
            get {
                return this.zPARTERN_CP1Field;
            }
            set {
                this.zPARTERN_CP1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPARTERN_CP2[] ZPARTERN_CP2 {
            get {
                return this.zPARTERN_CP2Field;
            }
            set {
                this.zPARTERN_CP2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_Dyn_PosCpSearch_resITEM[] ZCPQ_RESULT {
            get {
                return this.zCPQ_RESULTField;
            }
            set {
                this.zCPQ_RESULTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_PosCpSearch_resITEM {
        
        private string eXTERNAL_IDField;
        
        private string aCCOUNT_IDField;
        
        private string tEXT1Field;
        
        private string zCP_YHQField;
        
        private string zCP_NUMField;
        
        private string zCP_YHQDESField;
        
        private string zCP_TYPEField;
        
        private string zCP_PASSWField;
        
        private string zCP_BDATEField;
        
        private bool zCP_BDATEFieldSpecified;
        
        private string zCP_EDATEField;
        
        private bool zCP_EDATEFieldSpecified;
        
        private string zCP_JEField;
        
        private string zCP_ZKField;
        
        private string zCP_POINTField;
        
        private string zCP_PRODField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXTERNAL_ID {
            get {
                return this.eXTERNAL_IDField;
            }
            set {
                this.eXTERNAL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT1 {
            get {
                return this.tEXT1Field;
            }
            set {
                this.tEXT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_YHQ {
            get {
                return this.zCP_YHQField;
            }
            set {
                this.zCP_YHQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_NUM {
            get {
                return this.zCP_NUMField;
            }
            set {
                this.zCP_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_YHQDES {
            get {
                return this.zCP_YHQDESField;
            }
            set {
                this.zCP_YHQDESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_TYPE {
            get {
                return this.zCP_TYPEField;
            }
            set {
                this.zCP_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_PASSW {
            get {
                return this.zCP_PASSWField;
            }
            set {
                this.zCP_PASSWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_BDATE {
            get {
                return this.zCP_BDATEField;
            }
            set {
                this.zCP_BDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZCP_BDATESpecified {
            get {
                return this.zCP_BDATEFieldSpecified;
            }
            set {
                this.zCP_BDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_EDATE {
            get {
                return this.zCP_EDATEField;
            }
            set {
                this.zCP_EDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZCP_EDATESpecified {
            get {
                return this.zCP_EDATEFieldSpecified;
            }
            set {
                this.zCP_EDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_JE {
            get {
                return this.zCP_JEField;
            }
            set {
                this.zCP_JEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_ZK {
            get {
                return this.zCP_ZKField;
            }
            set {
                this.zCP_ZKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_POINT {
            get {
                return this.zCP_POINTField;
            }
            set {
                this.zCP_POINTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCP_PROD {
            get {
                return this.zCP_PRODField;
            }
            set {
                this.zCP_PRODField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_PosCpSearch_obCompletedEventHandler(object sender, si_PosCpSearch_obCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_PosCpSearch_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal si_PosCpSearch_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_Dyn_PosCpSearch_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_PosCpSearch_res)(this.results[0]));
            }
        }
    }
}
