//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     会员当前等级积分查询
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace Hmj.WebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Script.Serialization;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "si_Dyn_GetPoint_obBinding", Namespace = "http://jahwa.com/pos/crm")]
    public partial class si_Dyn_GetPoint_obService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback si_GetPoint_obOperationCompleted;

        /// <remarks/>
        public si_Dyn_GetPoint_obService()
        {
            this.Url = ConfigurationManager.AppSettings["WebServerURLTest"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_GetPoint_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUserTest"],
            ConfigurationManager.AppSettings["WebServerPassTest"]);
        }

        /// <remarks/>
        public event si_GetPoint_obCompletedEventHandler si_GetPoint_obCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_GetPoint_res", Namespace = "http://jahwa.com/pos/crm")]
        public dt_Dyn_GetPoint_res si_GetPoint_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")]
        dt_Dyn_GetPoint_req mt_Dyn_GetPoint_req)
        {
           

            object[] results = this.Invoke("si_GetPoint_ob", new object[] {
                        mt_Dyn_GetPoint_req});


            return ((dt_Dyn_GetPoint_res)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginsi_GetPoint_ob(dt_Dyn_GetPoint_req mt_Dyn_GetPoint_req, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("si_GetPoint_ob", new object[] {
                        mt_Dyn_GetPoint_req}, callback, asyncState);
        }

        /// <remarks/>
        public dt_Dyn_GetPoint_res Endsi_GetPoint_ob(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_GetPoint_res)(results[0]));
        }

        /// <remarks/>
        public void si_GetPoint_obAsync(dt_Dyn_GetPoint_req mt_Dyn_GetPoint_req)
        {
            this.si_GetPoint_obAsync(mt_Dyn_GetPoint_req, null);
        }

        /// <remarks/>
        public void si_GetPoint_obAsync(dt_Dyn_GetPoint_req mt_Dyn_GetPoint_req, object userState)
        {
            if ((this.si_GetPoint_obOperationCompleted == null))
            {
                this.si_GetPoint_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_GetPoint_obOperationCompleted);
            }
            this.InvokeAsync("si_GetPoint_ob", new object[] {
                        mt_Dyn_GetPoint_req}, this.si_GetPoint_obOperationCompleted, userState);
        }

        private void Onsi_GetPoint_obOperationCompleted(object arg)
        {
            if ((this.si_GetPoint_obCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_GetPoint_obCompleted(this, new si_GetPoint_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_GetPoint_req
    {

        private string aCCOUNT_IDField;

        private string lOY_POINT_CODEField;

        private string dATEField;

        //private bool dATEFieldSpecified;

        private string dATA_SOURCEField;

        private string vGROUPField;

        private string lOYALTY_BRANDField;

        private string sOURCE_SYSTEMField;

        private string pARTNERField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID
        {
            get
            {
                return this.aCCOUNT_IDField;
            }
            set
            {
                this.aCCOUNT_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOY_POINT_CODE
        {
            get
            {
                return this.lOY_POINT_CODEField;
            }
            set
            {
                this.lOY_POINT_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool DATESpecified
        //{
        //    get
        //    {
        //        return this.dATEFieldSpecified;
        //    }
        //    set
        //    {
        //        this.dATEFieldSpecified = value;
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE
        {
            get
            {
                return this.dATA_SOURCEField;
            }
            set
            {
                this.dATA_SOURCEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP
        {
            get
            {
                return this.vGROUPField;
            }
            set
            {
                this.vGROUPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND
        {
            get
            {
                return this.lOYALTY_BRANDField;
            }
            set
            {
                this.lOYALTY_BRANDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM
        {
            get
            {
                return this.sOURCE_SYSTEMField;
            }
            set
            {
                this.sOURCE_SYSTEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARTNER
        {
            get
            {
                return this.pARTNERField;
            }
            set
            {
                this.pARTNERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://jahwa.com/pos/crm")]
    public partial class ZCRMT405_Dyn
    {

        private string aCCOUNT_IDField;

        private string cLOS_NQUAL_PTSField;

        private string eXPIRE_POINTField;

        private string tIERSField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_ID
        {
            get
            {
                return this.aCCOUNT_IDField;
            }
            set
            {
                this.aCCOUNT_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLOS_NQUAL_PTS
        {
            get
            {
                return this.cLOS_NQUAL_PTSField;
            }
            set
            {
                this.cLOS_NQUAL_PTSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXPIRE_POINT
        {
            get
            {
                return this.eXPIRE_POINTField;
            }
            set
            {
                this.eXPIRE_POINTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIERS
        {
            get
            {
                return this.tIERSField;
            }
            set
            {
                this.tIERSField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_GetPoint_res
    {

        private ZCRMT405_Dyn[] zCRMT405_dynField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ZCRMT405_Dyn[] ZCRMT405_dyn
        {
            get
            {
                return this.zCRMT405_dynField;
            }
            set
            {
                this.zCRMT405_dynField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_GetPoint_obCompletedEventHandler(object sender, si_GetPoint_obCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_GetPoint_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal si_GetPoint_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public dt_Dyn_GetPoint_res Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_GetPoint_res)(this.results[0]));
            }
        }
    }
}
