//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace Hmj.WebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;
    using System.Web.Script.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_Dyn_ExchangeCard_obBinding", Namespace="http://jahwa.com/pos/crm")]
    public partial class si_Dyn_ExchangeCard_obService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_Dyn_ExchangeCard_obOperationCompleted;

        /// <remarks/>
        public si_Dyn_ExchangeCard_obService() {
            this.Url = ConfigurationManager.AppSettings["WebServerURLTest"] + "/sap/xi/engine?type=entry&version=3.0&Sender.Service=bs_pos&Int" +
                "erface=http%3A%2F%2Fjahwa.com%2Fpos%2Fcrm%5Esi_Dyn_ExchangeCard_ob";

            this.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["WebServerUserTest"],
            ConfigurationManager.AppSettings["WebServerPassTest"]);
        }
        
        /// <remarks/>
        public event si_Dyn_ExchangeCard_obCompletedEventHandler si_Dyn_ExchangeCard_obCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("mt_Dyn_ExchangeCard_res", Namespace="http://jahwa.com/pos/crm")]
        public dt_Dyn_ExchangeCard_res si_Dyn_ExchangeCard_ob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jahwa.com/pos/crm")]
        dt_Dyn_ExchangeCard_req mt_Dyn_ExchangeCard_req) {

            object[] results = this.Invoke("si_Dyn_ExchangeCard_ob", new object[] {
                        mt_Dyn_ExchangeCard_req});

            return ((dt_Dyn_ExchangeCard_res)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsi_Dyn_ExchangeCard_ob(dt_Dyn_ExchangeCard_req mt_Dyn_ExchangeCard_req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("si_Dyn_ExchangeCard_ob", new object[] {
                        mt_Dyn_ExchangeCard_req}, callback, asyncState);
        }
        
        /// <remarks/>
        public dt_Dyn_ExchangeCard_res Endsi_Dyn_ExchangeCard_ob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dt_Dyn_ExchangeCard_res)(results[0]));
        }
        
        /// <remarks/>
        public void si_Dyn_ExchangeCard_obAsync(dt_Dyn_ExchangeCard_req mt_Dyn_ExchangeCard_req) {
            this.si_Dyn_ExchangeCard_obAsync(mt_Dyn_ExchangeCard_req, null);
        }
        
        /// <remarks/>
        public void si_Dyn_ExchangeCard_obAsync(dt_Dyn_ExchangeCard_req mt_Dyn_ExchangeCard_req, object userState) {
            if ((this.si_Dyn_ExchangeCard_obOperationCompleted == null)) {
                this.si_Dyn_ExchangeCard_obOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_Dyn_ExchangeCard_obOperationCompleted);
            }
            this.InvokeAsync("si_Dyn_ExchangeCard_ob", new object[] {
                        mt_Dyn_ExchangeCard_req}, this.si_Dyn_ExchangeCard_obOperationCompleted, userState);
        }
        
        private void Onsi_Dyn_ExchangeCard_obOperationCompleted(object arg) {
            if ((this.si_Dyn_ExchangeCard_obCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_Dyn_ExchangeCard_obCompleted(this, new si_Dyn_ExchangeCard_obCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_ExchangeCard_req {
        
        private string dATA_SOURCEField;
        
        private string hYCARDField;
        
        private string hYCARD_OLDField;
        
        private string dEPTIDField;
        
        private string eMPIDField;
        
        private string vGROUPField;
        
        private string sOURCE_SYSTEMField;
        
        private string lOYALTY_BRANDField;
        
        private string mEMBER_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATA_SOURCE {
            get {
                return this.dATA_SOURCEField;
            }
            set {
                this.dATA_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HYCARD {
            get {
                return this.hYCARDField;
            }
            set {
                this.hYCARDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HYCARD_OLD {
            get {
                return this.hYCARD_OLDField;
            }
            set {
                this.hYCARD_OLDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPTID {
            get {
                return this.dEPTIDField;
            }
            set {
                this.dEPTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPID {
            get {
                return this.eMPIDField;
            }
            set {
                this.eMPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VGROUP {
            get {
                return this.vGROUPField;
            }
            set {
                this.vGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCE_SYSTEM {
            get {
                return this.sOURCE_SYSTEMField;
            }
            set {
                this.sOURCE_SYSTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOYALTY_BRAND {
            get {
                return this.lOYALTY_BRANDField;
            }
            set {
                this.lOYALTY_BRANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMBER_ID {
            get {
                return this.mEMBER_IDField;
            }
            set {
                this.mEMBER_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jahwa.com/pos/crm")]
    public partial class dt_Dyn_ExchangeCard_res {
        
        private string wV_RETURNField;
        
        private string wV_MESSAGEField;
        
        private string zHYCARDField;
        
        private string zHYCARD_OLDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WV_RETURN {
            get {
                return this.wV_RETURNField;
            }
            set {
                this.wV_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WV_MESSAGE {
            get {
                return this.wV_MESSAGEField;
            }
            set {
                this.wV_MESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZHYCARD {
            get {
                return this.zHYCARDField;
            }
            set {
                this.zHYCARDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZHYCARD_OLD {
            get {
                return this.zHYCARD_OLDField;
            }
            set {
                this.zHYCARD_OLDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void si_Dyn_ExchangeCard_obCompletedEventHandler(object sender, si_Dyn_ExchangeCard_obCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class si_Dyn_ExchangeCard_obCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal si_Dyn_ExchangeCard_obCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_Dyn_ExchangeCard_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_Dyn_ExchangeCard_res)(this.results[0]));
            }
        }
    }
}
